import { type ChangeEvent, useEffect, useMemo, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, BadgeCheck, CheckCircle2, Clock3, Download, Edit3, Eye, FileText, Files, Folder, FolderOpen, Inbox, Plus, RefreshCw, Search, Send, Share2, Trash2, X, XCircle, type LucideIcon } from 'lucide-react'
import TemplateWorkspace from './InstitutionalTemplateWorkspace'
import DocumentDetailView from './InstitutionalDocumentDetail'
import type {PortalSession} from '@/lib/session'
import {newLetterForm} from './institutionalLetterPdf'
import './institutionalDocuments.css'
import './institutionalBrandOverrides.css'

type Tab='chat'|'files'|'communications'|'templates'
type View='all'|'approved'|'departments'|'mine'|'shared'|'transit'|'received'|'rejected'|'sent'|'trash'
type Overview={total:number;mine:number;shared:number;received:number;pending:number;sent:number;rejected:number;departments:{name:string;count:number}[]}
type Share={id:number;recipientUserName?:string;recipientDepartment?:string;canEdit:boolean;sharedUtc:string}
export type DocumentItem={id:number;title:string;description?:string;originalFileName:string;contentType:string;size:number;ownerUserName:string;department:string;area?:string;channel?:string;recipientUserName?:string;recipientDepartment?:string;status:string;createdUtc:string;sentUtc?:string;receivedUtc?:string;isOwner:boolean;canEdit:boolean;sharedWith:Share[]}
export type DocumentHistory={action:string;actor:string;login:string;at:string;previousStatus:string;receiptCode?:string;receiverLogin?:string;receivedUtc?:string}
export type DocumentDetail=DocumentItem&{channel:string;fileUrl:string;ownerDisplayName:string;receiverDisplayName?:string;receiverLogin?:string;receivedByUserName?:string;receiptCode?:string;verificationToken?:string;sealX?:number;sealY?:number;receiptSignature?:string;correctionNote?:string;decisionBy?:string;decisionUtc?:string;history?:DocumentHistory[];isRecipient:boolean;canMove:boolean}
export type Template={id:number;name:string;content:string;department:string;ownerUserName:string;isSystem:boolean;updatedUtc:string}
export type DocumentUser={userName:string;fullName:string;department:string;email?:string;status?:string}
const emptyOverview:Overview={total:0,mine:0,shared:0,received:0,pending:0,sent:0,rejected:0,departments:[]}
const maintenanceDepartmentNames:Record<string,string>={TECHNOLOGY:'Tecnología',GENERAL_SERVICES:'Servicios Generales',HUMAN_RESOURCES:'Recursos Humanos'}
export function DocumentSystemModule({tab,title,description,initialView,channel='requests',session,scopeDepartment}:{tab:Tab;title:string;description:string;initialView?:View;channel?:'requests'|'requirements';session:PortalSession;scopeDepartment?:string}){
  const lockedDepartment=scopeDepartment?maintenanceDepartmentNames[scopeDepartment]||scopeDepartment:''
  const[overview,setOverview]=useState(emptyOverview),[department,setDepartment]=useState(lockedDepartment),[documents,setDocuments]=useState<DocumentItem[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true)
  const[view,setView]=useState<View>(lockedDepartment?(initialView||'transit'):(initialView||'departments')),[error,setError]=useState(''),[uploadOpen,setUploadOpen]=useState(false),[shareTarget,setShareTarget]=useState<DocumentItem|null>(null)
  const[busy,setBusy]=useState(false)
  const[detail,setDetail]=useState<DocumentDetail|null>(null),[sendTarget,setSendTarget]=useState<DocumentItem|null>(null)
  const[uploadTitle,setUploadTitle]=useState(''),[uploadDescription,setUploadDescription]=useState(''),[recipientDepartment,setRecipientDepartment]=useState(''),[recipientUser,setRecipientUser]=useState(''),[selectedFiles,setSelectedFiles]=useState<File[]>([])
  const[shareDepartment,setShareDepartment]=useState(''),[shareUser,setShareUser]=useState(''),[canEdit,setCanEdit]=useState(false)
  const[templates,setTemplates]=useState<Template[]>([]),[activeTemplate,setActiveTemplate]=useState<Template|null>(null),[templateName,setTemplateName]=useState(''),[templateContent,setTemplateContent]=useState('')
  const[documentUsers,setDocumentUsers]=useState<DocumentUser[]>([])
  const uploadInput=useRef<HTMLInputElement>(null)
  const area=tab==='communications'?'communications':'files'
  const warehouseManager=session.role==='Administrator'||session.supportTeam==='WAREHOUSE'
  const canCreate=area==='files'||(channel==='requests'&&!warehouseManager)
  const warehouseRequestInbox=area==='communications'&&channel==='requests'&&warehouseManager
  // Catálogo histórico completo: ['Tecnología','Servicios Generales','Recursos Humanos'].
  // El buzón de Almacén solo opera con Tecnología y Servicios Generales.
  const requestDepartments=overview.departments.filter(folder=>['Tecnología','Servicios Generales'].includes(folder.name))

  useEffect(()=>{setDepartment(lockedDepartment);setDocuments([]);setView(lockedDepartment?(initialView||'transit'):(initialView||'departments'));if(tab==='templates'){void loadTemplates();void loadOverview()}else void loadOverview();if(tab==='templates'||tab==='communications'||tab==='files')void loadDocumentUsers()},[tab,initialView,lockedDepartment])
  useEffect(()=>{if(department||view!=='departments')void loadDocuments()},[department,view])
  async function api(url:string,options?:RequestInit){const response=await fetch(url,{credentials:'include',cache:'no-store',...options});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.message||body.error||body.detail||'No se pudo consultar el módulo documental.')}return response.status===204?null:response.json()}
  async function run(action:()=>Promise<void>){setError('');try{await action();return true}catch(reason){setError(reason instanceof Error?reason.message:'Ocurrió un error inesperado.');return false}}
  async function loadOverview(){setLoading(true);await run(async()=>setOverview(await api(`/api/institutional-documents/overview?area=${area}&channel=${channel}`)));setLoading(false)}
  async function loadDocuments(){setLoading(true);await run(async()=>{
    // “Mis archivos” is the user's complete outbound history. Communications
    // are stored in two channels, while the Files area keeps its own uploads;
    // merge both sources here so nothing sent from Plantillas disappears.
    const urls=view==='mine'&&tab==='communications'
      ?[`/api/institutional-documents?area=communications&channel=all&view=mine${department?`&department=${encodeURIComponent(department)}`:''}`]
      :view==='mine'&&tab==='files'
        ?[`/api/institutional-documents?area=files&channel=requests&view=mine${department?`&department=${encodeURIComponent(department)}`:''}`,`/api/institutional-documents?area=communications&channel=all&view=mine`]
        :[`/api/institutional-documents?area=${area}&channel=${channel}&view=${view}${department?`&department=${encodeURIComponent(department)}`:''}`]
    const responses=await Promise.all(urls.map(url=>api(url) as Promise<DocumentItem[]>));
    setDocuments(responses.flat().sort((a,b)=>new Date(b.createdUtc).getTime()-new Date(a.createdUtc).getTime()))
  });setLoading(false)}
  async function loadTemplates(){setLoading(true);await run(async()=>setTemplates(await api('/api/institutional-documents/templates')));setLoading(false)}
  async function loadDocumentUsers(){await run(async()=>setDocumentUsers(await api('/api/institutional-documents/users')))}
  function chooseFile(event:ChangeEvent<HTMLInputElement>){setSelectedFiles(Array.from(event.target.files||[]))}
  async function upload(){if(!selectedFiles.length||busy)return;setBusy(true);await run(async()=>{for(const[fileIndex,file]of selectedFiles.entries()){const form=new FormData();form.append('file',file);form.append('area',area);form.append('channel',channel);form.append('department',department||'');form.append('title',selectedFiles.length===1&&uploadTitle?uploadTitle:file.name.replace(/\.[^.]+$/,''));form.append('description',uploadDescription);if(recipientDepartment)form.append('recipientDepartment',recipientDepartment);if(recipientUser)form.append('recipientUserName',recipientUser);await api('/api/institutional-documents',{method:'POST',body:form});setSelectedFiles(current=>current.filter(value=>value!==file));if(fileIndex===selectedFiles.length-1)continue}setUploadOpen(false);setSelectedFiles([]);setUploadTitle('');setUploadDescription('');setRecipientDepartment('');setRecipientUser('');await loadOverview();if(view!=='departments'||department)await loadDocuments()});setBusy(false)}
  async function action(id:number,name:string,body:object={}){await api(`/api/institutional-documents/${id}/actions/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
  async function setStatus(id:number,status:string){await run(async()=>{await action(id,status==='deleted'?'trash':'restore');await loadDocuments();await loadOverview()})}
  async function openDetail(item:DocumentItem){await run(async()=>setDetail(await api(`/api/institutional-documents/${item.id}`)))}
  async function refreshDetail(){if(!detail)return;setDetail(await api(`/api/institutional-documents/${detail.id}`));await loadDocuments();await loadOverview()}
  async function purge(id:number){if(!window.confirm('Este archivo se eliminará definitivamente. ¿Deseas continuar?'))return;await run(async()=>{await action(id,'purge');await loadDocuments();await loadOverview()})}
  async function edit(item:DocumentItem){const next=window.prompt('Nuevo título del documento:',item.title);if(!next?.trim())return;await run(async()=>{await action(item.id,'edit',{title:next,description:item.description});await loadDocuments()})}
  async function share(){if(!shareTarget||(!shareDepartment&&!shareUser))return;await run(async()=>{await action(shareTarget.id,'share',{recipientDepartment:shareDepartment,recipientUserName:shareUser||null,canEdit});setShareTarget(null);setShareDepartment('');setShareUser('');setCanEdit(false);await loadDocuments();await loadOverview()})}
  async function sendDraft(){if(!sendTarget||!recipientDepartment)return;await run(async()=>{await action(sendTarget.id,'send',{recipientDepartment,recipientUserName:recipientUser||null});setSendTarget(null);setRecipientDepartment('');setRecipientUser('');await loadDocuments();await loadOverview()})}
  async function unshare(shareId:number){if(!shareTarget)return;await run(async()=>{await action(shareTarget.id,'unshare',{shareId});const next={...shareTarget,sharedWith:shareTarget.sharedWith.filter(item=>item.id!==shareId)};setShareTarget(next);setDocuments(items=>items.map(item=>item.id===next.id?next:item));await loadOverview()})}
  async function saveTemplate(){let saved:Template|null=null;const ok=await run(async()=>{saved=await api('/api/institutional-documents/templates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:activeTemplate?.id||null,name:templateName,content:templateContent||JSON.stringify(newLetterForm())})}) as Template;setActiveTemplate(saved);await loadTemplates()});if(!ok||!saved)throw new Error('No se pudo guardar la plantilla.');return saved}
  async function archiveTemplatePdf(template:Template,data:Uint8Array){const form=new FormData();form.append('file',new Blob([data.slice().buffer],{type:'application/pdf'}),`${template.name||'comunicacion-real'}.pdf`);form.append('area','communications');form.append('channel','requests');form.append('draft','true');form.append('templateId',String(template.id));form.append('title',template.name);form.append('description','PDF archivado desde Plantillas');await api('/api/institutional-documents',{method:'POST',body:form})}
  async function deleteTemplate(id:number){if(!window.confirm('¿Eliminar esta plantilla guardada? Los documentos enviados se conservarán.'))return;await run(async()=>{await api(`/api/institutional-documents/templates/${id}`,{method:'DELETE'});setActiveTemplate(null);setTemplateName('');setTemplateContent('');await loadTemplates()})}
  function openTemplate(template?:Template){if(template&&(template.isSystem||template.ownerUserName!==session.id)){setActiveTemplate(null);setTemplateName(`Copia de ${template.name}`);setTemplateContent(template.content);return}const next=template||null;setActiveTemplate(next);setTemplateName(next?.name||'');setTemplateContent(next?.content||'')}
  const visible=useMemo(()=>documents.filter(item=>(item.title+' '+item.originalFileName+' '+item.ownerUserName+' '+(item.recipientDepartment||'')).toLowerCase().includes(query.toLowerCase())),[documents,query])
  const Icon=tab==='communications'?Send:tab==='templates'?Files:FolderOpen

  if(tab==='templates')return <TemplateWorkspace title={title} description={description} templates={templates} activeTemplate={activeTemplate} templateName={templateName} templateContent={templateContent} loading={loading} error={error} departments={overview.departments} users={documentUsers} onName={setTemplateName} onContent={setTemplateContent} onOpen={openTemplate} onSave={saveTemplate} onArchivePdf={archiveTemplatePdf} onDelete={deleteTemplate} api={api} session={session}/>

  if(warehouseRequestInbox&&!department&&view==='departments')return <section className="native-doc-page warehouse-request-inbox warehouse-folder-landing"><div className="native-doc-top"><DocHeader icon={Icon} title={title} description="Selecciona primero el departamento remitente para abrir su bandeja de solicitudes."/><button className="native-doc-refresh" disabled={loading||busy} onClick={()=>void loadOverview()}><RefreshCw/>Actualizar</button></div>{error&&<ErrorBar text={error}/>}<WarehouseRequestFolders folders={requestDepartments} loading={loading} onOpen={name=>{setDetail(null);setDepartment(name);setView('transit')}}/></section>

  return <section className={`native-doc-page${warehouseRequestInbox?' warehouse-request-inbox':''}`}><div className="native-doc-top"><DocHeader icon={Icon} title={title} description={description}/><button className="native-doc-refresh" disabled={loading||busy} onClick={()=>{void loadOverview();if(department||view!=='departments')void loadDocuments()}}><RefreshCw/>Actualizar</button></div>{error&&<ErrorBar text={error}/>}<input ref={uploadInput} hidden type="file" multiple={area==='files'} accept=".pdf,.png,.jpg,.jpeg,.docx,.xlsx,.txt" onChange={chooseFile}/>
    {!warehouseRequestInbox&&<div className="native-doc-view-tabs"><ViewButton active={view==='departments'} onClick={()=>{setDetail(null);setDepartment('');setView('departments')}} icon={Folder} label="Carpetas"/><ViewButton active={view==='mine'} onClick={()=>{setDetail(null);setDepartment('');setView('mine')}} icon={Files} label="Mis archivos"/><ViewButton active={view==='shared'} onClick={()=>{setDetail(null);setDepartment('');setView('shared')}} icon={Share2} label="Compartidos"/>{area==='communications'&&<><ViewButton active={view==='transit'} onClick={()=>{setDetail(null);setDepartment('');setView('transit')}} icon={Clock3} label="En tránsito"/><ViewButton active={view==='received'} onClick={()=>{setDetail(null);setDepartment('');setView('received')}} icon={Inbox} label="Recibidos"/><ViewButton active={view==='rejected'} onClick={()=>{setDetail(null);setDepartment('');setView('rejected')}} icon={XCircle} label="Rechazados"/><ViewButton active={view==='approved'} onClick={()=>{setDetail(null);setDepartment('');setView('approved')}} icon={CheckCircle2} label="Autorizados"/><ViewButton active={view==='sent'} onClick={()=>{setDetail(null);setDepartment('');setView('sent')}} icon={Send} label="Enviados"/></>}<ViewButton active={view==='trash'} onClick={()=>{setDetail(null);setDepartment('');setView('trash')}} icon={Trash2} label="Papelera"/></div>}
    {warehouseRequestInbox&&department&&<div className="warehouse-inbox-status-tabs" role="tablist" aria-label={`Bandejas de ${department}`}><ViewButton active={view==='all'} onClick={()=>{setDetail(null);setView('all')}} icon={Files} label="Todas"/><ViewButton active={view==='transit'} onClick={()=>{setDetail(null);setView('transit')}} icon={Clock3} label="En tránsito"/><ViewButton active={view==='received'} onClick={()=>{setDetail(null);setView('received')}} icon={Inbox} label="Recibidas"/><ViewButton active={view==='approved'} onClick={()=>{setDetail(null);setView('approved')}} icon={CheckCircle2} label="Autorizadas"/><ViewButton active={view==='rejected'} onClick={()=>{setDetail(null);setView('rejected')}} icon={XCircle} label="Rechazadas"/></div>}
    {!department&&view==='departments'?<><div className="native-doc-stats">{area==='communications'?<><Stat icon={Clock3} label="En tránsito" caption="Pendientes de recepción" value={overview.pending} tone="amber" onClick={()=>setView('transit')}/><Stat icon={BadgeCheck} label="Recepción" caption="Documentos sellados y QR" value={overview.received} tone="green" onClick={()=>setView('received')}/><Stat icon={Send} label="Enviadas" caption="Comunicaciones remitidas" value={overview.sent} tone="cyan" onClick={()=>setView('sent')}/><Stat icon={XCircle} label="Rechazadas" caption="Requieren seguimiento" value={overview.rejected} tone="red" onClick={()=>setView('rejected')}/><Stat icon={Share2} label="Compartidas" caption="Acceso colaborativo" value={overview.shared} tone="blue" onClick={()=>setView('shared')}/></>:<><Stat icon={Files} label="Total de archivos" caption="Documentos registrados" value={overview.total}/><Stat icon={FileText} label="Mis archivos" caption="Creados por mí" value={overview.mine} onClick={()=>setView('mine')}/><Stat icon={Share2} label="Compartidos" caption="Recibidos de otros usuarios" value={overview.shared} tone="blue" onClick={()=>setView('shared')}/><Stat icon={Folder} label="Departamentos" caption="Carpetas disponibles" value={overview.departments.length}/><Stat icon={CheckCircle2} label="Disponibles" caption="Archivos activos" value={Math.max(0,overview.total)} tone="green"/></>}</div><div className="native-doc-section-head"><div><h2>Carpetas por departamento</h2><p>Selecciona un departamento para consultar {area==='files'?'sus archivos':'su correspondencia'}.</p></div><button disabled={!canCreate} onClick={()=>{if(channel==='requests')setRecipientDepartment('Almacén');setUploadOpen(true)}}><Plus/>{area==='files'?'Subir archivo':'Nueva comunicación'}</button></div><div className="native-folder-grid">{loading?<p>Cargando departamentos…</p>:overview.departments.map(folder=><button onClick={()=>{setDetail(null);setDepartment(folder.name)}} key={folder.name}><span><Folder/></span><div><strong>{folder.name}</strong><small>{folder.count} {area==='files'?'archivos':'comunicaciones'}</small></div></button>)}</div></>
    :detail?<DocumentDetailView key={detail.id} item={detail} onBack={()=>setDetail(null)} onChanged={refreshDetail}/>:<><div className="native-folder-toolbar"><button onClick={()=>{setDetail(null);if(lockedDepartment){setView('transit');void loadDocuments()}else{setDepartment('');setView('departments');void loadOverview()}}}><ArrowLeft/>{lockedDepartment?'Actualizar carpeta':'Volver'}</button><div><Folder/><span><strong>{department||viewName(view)}</strong><small>{documents.length} documentos</small></span></div><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar documentos"/></label><button className="primary" disabled={!canCreate} onClick={()=>{if(channel==='requests')setRecipientDepartment('Almacén');setUploadOpen(true)}}><Plus/>Agregar</button></div><DocumentList items={visible} loading={loading} area={area} view={view} onOpen={openDetail} onStatus={setStatus} onEdit={edit} onShare={setShareTarget} onSend={setSendTarget} onPurge={purge}/></>}
    {uploadOpen&&<div className="native-doc-modal-backdrop"><div className="native-doc-modal native-upload-modal">{error&&<ErrorBar text={error}/>}<header><div><small>{area==='communications'?'NUEVA COMUNICACIÓN OFICIAL':'GESTOR DE ARCHIVOS'}</small><h2>{area==='communications'?'Enviar comunicación':'Subir documentos'}</h2></div><button onClick={()=>setUploadOpen(false)}><X/></button></header>{area==='communications'&&<label>Asunto<input value={uploadTitle} onChange={e=>setUploadTitle(e.target.value)} placeholder="Ej. Solicitud de revisión presupuestaria"/></label>}<label>Descripción<textarea value={uploadDescription} onChange={e=>setUploadDescription(e.target.value)} placeholder="Descripción o mensaje opcional"/></label>{area==='communications'&&<><label>Departamento destinatario<select value={recipientDepartment} onChange={e=>{setRecipientDepartment(e.target.value);setRecipientUser('')}}><option value="">Seleccionar departamento</option>{overview.departments.filter(x=>area!=='communications'||x.name!==department).map(x=><option key={x.name}>{x.name}</option>)}</select></label>{recipientDepartment&&<label>Persona destinataria<select value={recipientUser} onChange={e=>setRecipientUser(e.target.value)}><option value="">Todo el departamento</option>{documentUsers.filter(user=>user.department===recipientDepartment).map(user=><option key={user.userName} value={user.userName}>{user.fullName}{user.email?` · ${user.email}`:''}</option>)}</select></label>}</>}<button className="native-file-picker" onClick={()=>uploadInput.current?.click()}><FileText/><span><strong>{selectedFiles.length?`${selectedFiles.length} archivo${selectedFiles.length===1?'':'s'} seleccionado${selectedFiles.length===1?'':'s'}`:area==='files'?'Seleccionar uno o varios archivos':'Adjuntar documento'}</strong><small>{selectedFiles.map(file=>file.name).join(' · ')||'PDF, PNG, JPG, DOCX, XLSX o TXT · máximo 10 MB por archivo'}</small></span></button><footer><button onClick={()=>setUploadOpen(false)}>Cancelar</button><button className="primary" disabled={busy||!selectedFiles.length||(area==='communications'&&(!recipientDepartment||!uploadTitle.trim()))} onClick={upload}>{area==='communications'?<><Send/>Enviar comunicación</>:<>Guardar {selectedFiles.length||''}</>}</button></footer></div></div>}
    {shareTarget&&<div className="native-doc-modal-backdrop"><div className="native-doc-modal native-share-modal">{error&&<ErrorBar text={error}/>}<header><div><small>ACCESO COLABORATIVO</small><h2>Compartir “{shareTarget.title}”</h2></div><button onClick={()=>setShareTarget(null)}><X/></button></header><p>Comparte con todo un departamento o elige una persona específica.</p><label>Departamento<select value={shareDepartment} onChange={e=>{setShareDepartment(e.target.value);setShareUser('')}}><option value="">Seleccionar departamento</option>{overview.departments.map(x=><option key={x.name}>{x.name}</option>)}</select></label>{shareDepartment&&<label>Usuario específico (opcional)<select value={shareUser} onChange={e=>setShareUser(e.target.value)}><option value="">Todo el departamento</option>{documentUsers.filter(user=>user.department===shareDepartment).map(user=><option value={user.userName} key={user.userName}>{user.fullName}{user.email?` · ${user.email}`:''}</option>)}</select></label>}<div className="native-share-permissions"><button className={!canEdit?'active':''} onClick={()=>setCanEdit(false)}><Eye/><span><strong>Solo lectura</strong><small>Puede consultar y descargar</small></span></button><button className={canEdit?'active':''} onClick={()=>setCanEdit(true)}><Edit3/><span><strong>Puede editar</strong><small>Puede cambiar datos del archivo</small></span></button></div>{shareTarget.sharedWith.length>0&&<div className="native-share-current"><strong>Accesos actuales</strong>{shareTarget.sharedWith.map(item=><span key={item.id}><Share2/>{item.recipientUserName||item.recipientDepartment}<small>{item.canEdit?'Edición':'Lectura'}</small><button title="Quitar acceso" onClick={()=>void unshare(item.id)}><X/></button></span>)}</div>}<footer><button onClick={()=>setShareTarget(null)}>Cancelar</button><button className="primary" disabled={!shareDepartment&&!shareUser} onClick={share}><Share2/>Compartir acceso</button></footer></div></div>}
    {sendTarget&&<div className="native-doc-modal-backdrop"><div className="native-doc-modal"><header><div><small>PDF ARCHIVADO DESDE PLANTILLAS</small><h2>Enviar documento</h2></div><button onClick={()=>setSendTarget(null)}><X/></button></header><p>Selecciona el departamento que recibirá “{sendTarget.title}”.</p><label>Departamento<select value={recipientDepartment} onChange={e=>{setRecipientDepartment(e.target.value);setRecipientUser('')}}><option value="">Seleccionar departamento</option>{overview.departments.filter(x=>x.name!==department).map(x=><option key={x.name}>{x.name}</option>)}</select></label>{recipientDepartment&&<label>Persona destinataria<select value={recipientUser} onChange={e=>setRecipientUser(e.target.value)}><option value="">Todo el departamento</option>{documentUsers.filter(user=>user.department===recipientDepartment).map(user=><option key={user.userName} value={user.userName}>{user.fullName}</option>)}</select></label>}<footer><button onClick={()=>setSendTarget(null)}>Cancelar</button><button className="primary" disabled={busy||!recipientDepartment} onClick={()=>void sendDraft()}><Send/>Enviar</button></footer></div></div>}
  </section>
}

function WarehouseRequestFolders({folders,loading,onOpen}:{folders:Overview['departments'];loading:boolean;onOpen:(name:string)=>void}){
 const accents:Record<string,string>={'Tecnología':'technology','Servicios Generales':'services'}
 return <section className="warehouse-folder-selection"><header><span>ALMACÉN · SOLICITUDES POR DEPARTAMENTO</span><h2>Selecciona una carpeta</h2><p>Cada carpeta contiene exclusivamente las solicitudes y documentos enviados por ese departamento. Al abrirla podrás revisar su tránsito, recepción o rechazo.</p></header><div className="warehouse-folder-grid">{loading?<div className="native-doc-empty"><RefreshCw className="spin"/><h3>Cargando carpetas…</h3></div>:folders.map(folder=><button type="button" key={folder.name} className={accents[folder.name]||''} onClick={()=>onOpen(folder.name)}><span className="warehouse-folder-icon"><FolderOpen/></span><em>DEPARTAMENTO</em><strong>{folder.name}</strong><small>{folder.count} {folder.count===1?'comunicación':'comunicaciones'} registradas</small><b>Abrir bandeja <ArrowRight/></b></button>)}</div></section>
}


function DocumentList({items,loading,area,view,onOpen,onStatus,onEdit,onShare,onSend,onPurge}:{items:DocumentItem[];loading:boolean;area:string;view:View;onOpen:(item:DocumentItem)=>void;onStatus:(id:number,status:string)=>void;onEdit:(item:DocumentItem)=>void;onShare:(item:DocumentItem)=>void;onSend?:(item:DocumentItem)=>void;onPurge:(id:number)=>void}){return <div className="native-document-list">{loading?<p>Cargando documentos…</p>:items.length===0?<div className="native-doc-empty"><FileText/><h3>No hay documentos en esta vista</h3><p>Los documentos aparecerán aquí cuando se registren.</p></div>:items.map(item=><article key={item.id}><span><FileText/></span><div><strong>{item.title}</strong><small>{item.originalFileName} · {(item.size/1024).toFixed(1)} KB · {new Date(item.createdUtc).toLocaleDateString('es-DO',{timeZone:'America/Santo_Domingo'})}</small><p>{item.description}{item.recipientDepartment?` · Destino: ${item.recipientDepartment}`:''}</p></div><b className={`doc-status ${item.status}`}>{statusName(item.status)}</b>{view!=='trash'&&<button className="primary" onClick={()=>onOpen(item)}><FileText/>{(item.area||area)==='communications'?'Ver y responder':'Ver archivo'}</button>}<a href={`/api/institutional-documents/${item.id}/download`}><Download/>Descargar</a>{item.status==='draft'&&item.isOwner&&view!=='trash'&&onSend&&<button className="primary" onClick={()=>onSend(item)}><Send/>Enviar</button>}{item.canEdit&&view!=='trash'&&<button onClick={()=>onEdit(item)}><Edit3/>Editar</button>}{item.isOwner&&view!=='trash'&&<><button onClick={()=>onShare(item)}><Share2/>Compartir</button><button className="reject" onClick={()=>onStatus(item.id,'deleted')}><Trash2/>Papelera</button></>}{view==='trash'&&<><button onClick={()=>onStatus(item.id,'active')}><CheckCircle2/>Restaurar</button><button className="reject" onClick={()=>onPurge(item.id)}><Trash2/>Eliminar</button></>}</article>)}</div>}


function DocHeader({title,description}:{icon:LucideIcon;title:string;description:string}){return <><nav className="native-doc-breadcrumb" aria-label="Ruta de navegación"><span>Inicio</span><b>›</b><span>Documentos</span><b>›</b><strong>{title.replace('Mis Documentos · ','')}</strong></nav><div className="native-doc-header"><div><h1>{title}</h1><p>{description}</p></div></div></>}
function Stat({icon:Icon,label,caption='Documentos registrados',value,tone='blue',onClick}:{icon:LucideIcon;label:string;caption?:string;value:number;tone?:string;onClick?:()=>void}){const content=<><span><Icon/></span><div><strong>{label}</strong><small>{caption}</small></div><b>{value}</b></>;return onClick?<button type="button" className={`native-doc-stat ${tone} interactive`} onClick={onClick}>{content}</button>:<article className={`native-doc-stat ${tone}`}>{content}</article>}
function ViewButton({active,onClick,icon:Icon,label}:{active:boolean;onClick:()=>void;icon:LucideIcon;label:string}){return <button className={active?'active':''} onClick={onClick}><Icon/>{label}</button>}
function ErrorBar({text}:{text:string}){return <div role="alert" className="native-doc-error"><XCircle/>{text}</div>}
function viewName(view:View){return({all:'Todas las solicitudes',mine:'Mis archivos',shared:'Carpeta compartida',approved:'Autorizados',transit:'En tránsito',received:'Recibidos',rejected:'Rechazados',sent:'Enviados',trash:'Papelera',departments:'Carpetas'} as Record<View,string>)[view]}
function statusName(status:string){return({approved:'Autorizado',active:'Disponible',draft:'Borrador',pending:'En tránsito',received:'Recibido',sent:'Enviado',rejected:'Rechazado',correction_requested:'Corrección solicitada',deleted:'En papelera'} as Record<string,string>)[status]||status}
