import {jsPDF} from 'jspdf';
export type LetterForm={departmentHeading:string;referenceCode:string;documentDate:string;recipientName:string;recipientTitle:string;viaName:string;viaTitle:string;subject:string;body:string;closing:string;signerName:string;signerTitle:string;initials:string};
export const newLetterForm=():LetterForm=>({departmentHeading:'Departamento',referenceCode:`REAL-${new Date().getFullYear()}-`,documentDate:new Date().toLocaleDateString('es-DO',{timeZone:'America/Santo_Domingo'}),recipientName:'',recipientTitle:'',viaName:'',viaTitle:'',subject:'',body:'',closing:'Atentamente,',signerName:'',signerTitle:'',initials:''});
export function parseLetterForm(value:string):LetterForm{const next=newLetterForm();try{const parsed=JSON.parse(value);for(const k of Object.keys(next) as (keyof LetterForm)[])if(typeof parsed?.[k]==='string')next[k]=parsed[k]}catch{if(value)next.body=value}return next}
export function buildInstitutionalLetter(form:LetterForm,signature='',logo='',brandSeal=false,point={x:65,y:72},login=''){
 const pdf=new jsPDF();pdf.setProperties({title:form.subject||'Comunicación institucional',subject:'REAL-LETTER-V274',creator:'REAL · Grupo Tejeda'});let y=52;
 function header(){pdf.setFillColor(15,34,55);pdf.rect(12,10,186,28,'F');if(logo)pdf.addImage(logo,'PNG',17,18,30,11);else{pdf.setTextColor(255,213,26);pdf.setFontSize(19);pdf.text('REAL',18,28)}pdf.setTextColor(255);pdf.setFont('helvetica','bold');pdf.setFontSize(18);pdf.text('Grupo Tejeda',54,24);pdf.setFontSize(8);pdf.text('OFICINA VIRTUAL | COMUNICACIÓN INTERNA',54,31);pdf.setTextColor(20,50,78);pdf.setFontSize(11);const heading=pdf.splitTextToSize(form.departmentHeading,184);pdf.text(heading,13,45);y=Math.max(54,45+heading.length*5)}
 function ensure(height:number){if(y+height>230){pdf.addPage();header()}}
 function lines(value:string,bold=false){pdf.setFont('helvetica',bold?'bold':'normal');pdf.setFontSize(10);for(const block of value.split('\n')){for(const line of pdf.splitTextToSize(block||' ',181)){ensure(5);pdf.text(line,15,y);y+=5}y+=2}}
 header();lines(`Referencia: ${form.referenceCode}    |    Fecha: ${form.documentDate}`,true);y+=4;lines(`A: ${form.recipientName}${form.recipientTitle?' / '+form.recipientTitle:''}`);if(form.viaName)lines(`Vía: ${form.viaName}${form.viaTitle?' / '+form.viaTitle:''}`);lines(`Asunto: ${form.subject}`,true);y+=5;
 const parts=form.body.split(/\n\s*--- SALTO DE PÁGINA ---\s*\n/g);parts.forEach((part,index)=>{if(index){pdf.addPage();header()}lines(part)});lines(form.closing);ensure(8);
 if(brandSeal){pdf.setDrawColor(37,109,144);pdf.setTextColor(37,109,144);const sx=Math.max(12,Math.min(139,point.x/100*210)),sy=Math.max(55,Math.min(198,point.y/100*297));pdf.roundedRect(sx,sy,59,24,2,2);pdf.setFontSize(9);pdf.text('REAL · GRUPO TEJEDA',sx+3,sy+7);pdf.setFontSize(7);pdf.text('DOCUMENTO INTERNO',sx+3,sy+13);pdf.text('Sello de marca - no acredita recepción',sx+3,sy+19)}
 pdf.setTextColor(20,50,78);for(const[x,label]of [[15,'FIRMA DE QUIEN ENTREGA'],[111,'FIRMA DE QUIEN RECIBE']] as const){pdf.setDrawColor(177,194,207);pdf.roundedRect(x,239,84,37,1,1);pdf.setFontSize(8);pdf.setFont('helvetica','bold');pdf.text(label,x+3,245);pdf.line(x+3,265,x+81,265)}
 if(signature)pdf.addImage(signature,'PNG',19,247,74,17);pdf.setFont('helvetica','normal');pdf.setFontSize(7);pdf.text(pdf.splitTextToSize(form.signerName,77).slice(0,2),18,269);pdf.text(pdf.splitTextToSize(form.signerTitle,77).slice(0,1),18,275);pdf.text('Pendiente de firma del destinatario',114,270);
 // Long signature metadata is kept in the body rather than clipped from the record.
 pdf.setProperties({subject:`REAL-LETTER-V274|SIGNATURE_PAGE=${pdf.getNumberOfPages()}`});
 if(login.length>70||form.initials||form.signerName.length>45||form.signerTitle.length>55){pdf.addPage();header();lines('Identificación de entrega',true);lines(`Responsable: ${form.signerName}\nCargo: ${form.signerTitle}\nCuenta: ${login}\nIniciales: ${form.initials}`)}else if(login){pdf.setFontSize(6);pdf.text(`Cuenta de entrega: ${login}`,15,280)}
 for(let p=1;p<=pdf.getNumberOfPages();p++){pdf.setPage(p);pdf.setFontSize(7);pdf.setTextColor(90,108,124);pdf.text('REAL · Grupo Tejeda | Constancia interna, no es comprobante fiscal.',13,285);pdf.text(`${p} / ${pdf.getNumberOfPages()}`,185,285)}return pdf;
}
export async function realLogoData(){const r=await fetch('/loto-real-logo-transparent.png');if(!r.ok)throw new Error('No se pudo cargar el logo REAL.');const blob=await r.blob();return await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(blob)})}
export function downloadDocument(data:Uint8Array,name:string){const url=URL.createObjectURL(new Blob([data.slice().buffer],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
