import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';
import QRCode from 'qrcode';
import type {DocumentDetail} from './DocumentSystemModule';
export async function buildReceiptCopy(original:Uint8Array,item:DocumentDetail,logo:string,origin:string){
 const pdf=await PDFDocument.load(original);if(!item.receivedUtc)return original.slice();const font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),brand=await pdf.embedPng(logo),qr=await pdf.embedPng(await QRCode.toDataURL(`${origin}/api/institutional-documents/verify/${item.verificationToken}`,{width:180,margin:1}));
 const page=pdf.getPages()[0],{width,height}=page.getSize(),w=Math.min(220,width-16),h=107,x=Math.max(8,Math.min(width-w-8,(item.sealX??65)/100*width)),y=Math.max(8,Math.min(height-h-8,height-(item.sealY??72)/100*height-h));
 const safe=(s:string)=>s.replace(/[^\x20-\x7e\xa0-\xff]/g,'-');const time=new Date(item.receivedUtc).toLocaleString('es-DO',{timeZone:'America/Santo_Domingo'});const blue=rgb(.06,.24,.36);
 const fit=(value:string,size:number,max:number)=>{let result=safe(value);while(font.widthOfTextAtSize(result,size)>max&&result.length>1)result=result.slice(0,-1);return result};
 page.drawRectangle({x,y,width:w,height:h,color:rgb(1,1,1),borderColor:blue,borderWidth:1.5});page.drawImage(brand,{x:x+8,y:y+h-22,width:35,height:13});page.drawText('GRUPO TEJEDA',{x:x+49,y:y+h-17,size:10,font:bold,color:blue});page.drawText('RECIBIDO',{x:x+8,y:y+h-39,size:14,font:bold,color:blue});page.drawImage(qr,{x:x+w-53,y:y+5,width:48,height:48});
 for(const [n,text]of [time,item.receiverDisplayName||'',item.receiverLogin||'',item.receiptCode||''].entries())page.drawText(fit(text,7,w-65),{x:x+8,y:y+h-53-n*12,size:7,font,color:blue});
 const marker=pdf.getSubject()?.match(/REAL-LETTER-V274\|SIGNATURE_PAGE=(\d+)/);if(item.receiptSignature&&marker){const target=pdf.getPages()[Number(marker[1])-1];if(target){const mm=72/25.4;const sign=await pdf.embedPng(item.receiptSignature);target.drawRectangle({x:113*mm,y:(297-275)*mm,width:79*mm,height:28*mm,color:rgb(1,1,1)});target.drawImage(sign,{x:115*mm,y:(297-264)*mm,width:74*mm,height:17*mm});target.drawText(fit(item.receiverDisplayName||'',7,210),{x:114*mm,y:(297-269)*mm,size:7,font});target.drawText(fit(item.receiverLogin||'',6,210),{x:114*mm,y:(297-274)*mm,size:6,font});}}
 // Full metadata is preserved in an annex; originals are never overwritten.
 const receipt=pdf.addPage([595,842]);receipt.drawImage(brand,{x:40,y:777,width:80,height:30});receipt.drawText('Grupo Tejeda | Constancia de recepción',{x:140,y:790,size:16,font:bold,color:blue});let lineY=738;
 for(const text of [`Documento: ${item.title}`,`Código: ${item.receiptCode}`,`Recibido por: ${item.receiverDisplayName}`,`Login: ${item.receiverLogin}`,`Fecha y hora (República Dominicana): ${time}`,`Estado actual: ${item.status}`,`Verificación con sesión autorizada:`,`${origin}/api/institutional-documents/verify/${item.verificationToken}`]){let rest=safe(text);while(rest){const line=fit(rest,10,510);receipt.drawText(line,{x:40,y:lineY,size:10,font,color:blue});rest=rest.slice(line.length);lineY-=16}lineY-=10}
 if(item.receiptSignature){const sign=await pdf.embedPng(item.receiptSignature);receipt.drawImage(sign,{x:40,y:lineY-70,width:220,height:66});receipt.drawText('Firma de quien recibe',{x:40,y:lineY-85,size:10,font:bold,color:blue})}receipt.drawImage(qr,{x:430,y:80,width:110,height:110});receipt.drawText('Copia con constancia interna. El archivo original se conserva sin modificaciones.',{x:40,y:40,size:8,font,color:blue});if(marker){pdf.getPages().forEach((p,i)=>{p.drawRectangle({x:507,y:20,width:58,height:22,color:rgb(1,1,1)});p.drawText(`${i+1} / ${pdf.getPageCount()}`,{x:525,y:31,size:8,font,color:blue})})}return new Uint8Array(await pdf.save());
}
