import {useEffect,useRef,useState} from 'react';
import {X,PenLine,Save} from 'lucide-react';
import InstitutionalBrand from './InstitutionalBrand';
import {maintenanceApi} from './maintenanceApi';
export default function InstitutionalSignature({onUse,onClose}:{onUse:(data:string)=>Promise<void>;onClose:()=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),dirty=useRef(false);const[saved,setSaved]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{void maintenanceApi<{signatureData?:string}>('/api/account/saved-signature').then(d=>setSaved(d.signatureData||'')).catch(e=>setError(e.message))},[]);
 async function use(data:string,save:boolean){if(busy)return;setBusy(true);setError('');try{if(save)await maintenanceApi('/api/account/saved-signature','PUT',{signatureData:data});await onUse(data);onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="native-doc-modal-backdrop"><section className="native-doc-modal id-signature" role="dialog" aria-modal="true" aria-label="Firma personal" onKeyDown={e=>{if(e.key==='Escape'&&!busy)onClose()}}><header><InstitutionalBrand/><button onClick={onClose} disabled={busy} aria-label="Cerrar firma"><X/></button></header><h2>Firma personal</h2><p>Dibuja tu propia firma. Guardarla permite reutilizarla solo desde tu cuenta.</p>{error&&<p role="alert" className="native-doc-error">{error}</p>}{saved&&<div className="native-saved-signature"><img src={saved} alt="Mi firma guardada"/><button disabled={busy} onClick={()=>void use(saved,false)}>Usar mi firma guardada</button></div>}<canvas ref={canvas} width={800} height={240} aria-label="Dibuja tu firma" onPointerDown={e=>{drawing.current=true;e.currentTarget.setPointerCapture(e.pointerId);const r=e.currentTarget.getBoundingClientRect(),c=e.currentTarget.getContext('2d')!;c.strokeStyle='#173e66';c.lineWidth=3;c.lineCap='round';c.beginPath();c.moveTo((e.clientX-r.left)*800/r.width,(e.clientY-r.top)*240/r.height)}} onPointerMove={e=>{if(!drawing.current)return;dirty.current=true;const r=e.currentTarget.getBoundingClientRect(),c=e.currentTarget.getContext('2d')!;c.lineTo((e.clientX-r.left)*800/r.width,(e.clientY-r.top)*240/r.height);c.stroke()}} onPointerUp={()=>drawing.current=false} onPointerCancel={()=>drawing.current=false}/><footer><button disabled={busy} onClick={()=>{canvas.current?.getContext('2d')?.clearRect(0,0,800,240);dirty.current=false}}>Limpiar</button><button disabled={busy} onClick={()=>dirty.current?void use(canvas.current!.toDataURL('image/png'),false):setError('Dibuja la firma antes de usarla.')}><PenLine/>Usar una vez</button><button className="primary" disabled={busy} onClick={()=>dirty.current?void use(canvas.current!.toDataURL('image/png'),true):setError('Dibuja la firma antes de guardarla.')}><Save/>Guardar y usar</button></footer></section></div>
}
