import {useCallback,useEffect,useState} from "react";
import {Archive,Download,Eye,FileText,FolderOpen,Grid2X2,List,Plus,RefreshCw,Search,Upload,X} from "lucide-react";
import type {PortalSession} from "@/lib/session";
import {maintenanceApi} from "./maintenanceApi";
import {departmentLabels,formatDocumentTime} from "./maintenanceDocumentPdf";
import PdfFilePreview from "./PdfFilePreview";
type Template={id:string;title:string;description?:string;category:string;department:string;originalName:string;size?:number;createdByName:string;createdAt?:string;archived?:boolean;url?:string;builtin?:boolean};
const categories:Record<string,string>={FORMS:"Formularios y plantillas",POLICIES:"Normas y procedimientos",NOTICES:"Comunicados"};
const builtins:Template[]=[
 {id:"institutional-form",title:"Conduce institucional - dos firmas",description:"Formulario REAL / Grupo Tejeda para entrega y recepción de equipos. Dos espacios de firma y sello de recibido.",category:"FORMS",department:"ALL",originalName:"plantilla-conduce-institucional.pdf",createdByName:"REAL / Grupo Tejeda",url:"/documents/plantilla-conduce-institucional.pdf",builtin:true},
 {id:"workshop-slip",title:"Conduce de Taller - referencia original",description:"Formulario de reparaciones convertido desde el Excel suministrado. Se conserva como referencia.",category:"FORMS",department:"ALL",originalName:"conduce-taller-grupo-samana.pdf",createdByName:"Archivo institucional",url:"/documents/conduce-taller-grupo-samana.pdf",builtin:true},
 {id:"warehouse-manual",title:"Manual de normas y procedimientos",description:"Políticas y procesos de suministro, compras e inventario. Documento original sin modificaciones.",category:"POLICIES",department:"ALL",originalName:"manual-normas-politicas-procedimientos-almacen.pdf",createdByName:"Archivo institucional",url:"/documents/manual-normas-politicas-procedimientos-almacen.pdf",builtin:true},
 {id:"damage-notice",title:"Comunicado de Averías",description:"Información y evidencias requeridas para procesar equipos destinados a agencias. Documento original.",category:"NOTICES",department:"ALL",originalName:"comunicado-averias.pdf",createdByName:"Archivo institucional",url:"/documents/comunicado-averias.pdf",builtin:true},
];
export default function MaintenanceTemplates({session}:{session:PortalSession}){
 const manage=session.role==="Administrator"||session.supportTeam==="WAREHOUSE";
 const [files,setFiles]=useState<Template[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[category,setCategory]=useState("ALL"),[department,setDepartment]=useState("ALL"),[view,setView]=useState("list"),[sort,setSort]=useState("recent"),[archived,setArchived]=useState(false),[preview,setPreview]=useState<Template|null>(null),[upload,setUpload]=useState(false),[target,setTarget]=useState<Template|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const [draft,setDraft]=useState({title:"",description:"",category:"FORMS",department:"ALL"}),[file,setFile]=useState<File|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const items=await maintenanceApi<Template[]>("/api/maintenance/templates");setFiles(Array.isArray(items)?items:[]);setError("");}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener("support-live-refresh",refresh);return()=>window.removeEventListener("support-live-refresh",refresh);},[load]);
 const items=[...builtins,...files].filter(item=>!!item.archived===archived);
 const visible=items.filter(item=>(category==="ALL"||item.category===category)&&(department==="ALL"||item.department===department||item.department==="ALL")&&`${item.title} ${item.description||""} ${item.originalName}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).sort((a,b)=>sort==="name"?a.title.localeCompare(b.title,"es"):(b.createdAt||"").localeCompare(a.createdAt||""));
 const url=(item:Template)=>item.url||`/api/maintenance/templates/${item.id}/file`;
 async function publish(){if(!file||file.size>10485760){setError("Selecciona un PDF de hasta 10 MB.");return;}setBusy(true);setError("");try{const body=new FormData();body.append("file",file);Object.entries(draft).forEach(([key,value])=>body.append(key,value));const response=await fetch("/api/maintenance/templates",{method:"POST",body,credentials:"same-origin"});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"No se pudo publicar el archivo.");setUpload(false);setFile(null);setDraft({title:"",description:"",category:"FORMS",department:"ALL"});setNotice("Plantilla publicada en la biblioteca.");await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function archive(){if(!target)return;setBusy(true);try{await maintenanceApi(`/api/maintenance/templates/${target.id}/archive`,"POST",{archived:!target.archived});setNotice(target.archived?"Archivo restaurado.":"Archivo retirado del catálogo. Puedes recuperarlo en Archivados.");setTarget(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="mc-catalog"><header className="mc-page-heading"><div><small>BIBLIOTECA INSTITUCIONAL</small><h3>Plantillas y archivos</h3><p>Busca, consulta y descarga los documentos de tus procesos.</p></div><div className="mw-toolbar"><button onClick={()=>void load()} disabled={loading}><RefreshCw/> Actualizar</button>{manage&&<button className="primary" onClick={()=>{setError("");setUpload(true);}}><Plus/> Publicar PDF</button>}</div></header>
 <div className="mc-searchbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar plantilla, documento o contenido…" aria-label="Buscar archivos"/></label><select aria-label="Departamento" value={department} onChange={e=>setDepartment(e.target.value)}><option value="ALL">Todos los departamentos</option>{Object.entries(departmentLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><select aria-label="Ordenar documentos" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Más recientes</option><option value="name">Nombre A–Z</option></select><div className="mc-view-switch"><button aria-label="Vista de lista" aria-pressed={view==="list"} onClick={()=>setView("list")}><List/></button><button aria-label="Vista de tarjetas" aria-pressed={view==="cards"} onClick={()=>setView("cards")}><Grid2X2/></button></div></div>
 {error&&<p className="mw-error" role="alert">{error}</p>}{notice&&<p className="mw-notice" role="status">{notice}</p>}
 <div className="mc-catalog-layout"><main><div className="mc-results"><strong>{archived?"Archivos retirados":categories[category]||"Todos los archivos"}</strong><span>{visible.length} documentos</span></div><div className={`mc-files ${view}`}>{visible.map(item=><article key={item.id}><button className="mc-file-icon" onClick={()=>setPreview(item)} aria-label={`Vista previa: ${item.title}`}><FileText/><b>PDF</b></button><div className="mc-file-copy"><small>{categories[item.category]}</small><h4>{item.title}</h4><p>{item.description}</p><div className="mc-file-meta"><span>{departmentLabels[item.department]||"Todos los departamentos"}</span><span>{item.size?`${(item.size/1024).toFixed(0)} KB`:"Documento institucional"}</span><span>{item.createdAt?formatDocumentTime(item.createdAt):item.createdByName}</span></div></div><footer><button onClick={()=>setPreview(item)}><Eye/> Vista previa</button><a href={url(item)} download><Download/> Descargar</a>{manage&&!item.builtin&&<button onClick={()=>{setError("");setTarget(item);}}><Archive/>{item.archived?"Restaurar":"Retirar"}</button>}</footer></article>)}</div>{!visible.length&&<div className="mc-empty"><FolderOpen/><h4>No hay archivos con estos filtros</h4><p>Cambia la categoría o la búsqueda.</p></div>}</main><aside><section className="mc-side-panel"><h4>Categorías</h4><button className={category==="ALL"?"active":""} onClick={()=>setCategory("ALL")}><FolderOpen/>Todos los archivos<b>{items.length}</b></button>{Object.entries(categories).map(([key,label])=><button className={category===key?"active":""} key={key} onClick={()=>setCategory(key)}><FileText/>{label}<b>{items.filter(item=>item.category===key).length}</b></button>)}</section>{manage&&<section className="mc-side-panel"><h4>Administrar biblioteca</h4><button className={!archived?"active":""} onClick={()=>setArchived(false)}>Publicados<b>{builtins.length+files.filter(item=>!item.archived).length}</b></button><button className={archived?"active":""} onClick={()=>setArchived(true)}>Archivados<b>{files.filter(item=>item.archived).length}</b></button><p>Retirar conserva el archivo y permite restaurarlo. Los documentos originales están protegidos.</p></section>}<section className="mc-help-card"><FileText/><h4>Dos firmas, un formulario</h4><p>La plantilla institucional tiene campos separados para quien entrega y quien recibe.</p><button onClick={()=>setPreview(builtins[0])}>Ver plantilla de conduce</button></section></aside></div>
 {preview&&<PdfFilePreview url={url(preview)} title={preview.title} onClose={()=>setPreview(null)}/>}
 {(upload||target)&&<div className="mw-overlay"><section className="mw-form-panel" role="dialog" aria-modal="true" aria-labelledby="template-modal-title" onKeyDown={e=>{if(e.key==="Escape"&&!busy){setUpload(false);setTarget(null);}if(e.key==="Tab"){const nodes=e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)'),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><header><h3 id="template-modal-title">{target?target.archived?"Restaurar archivo":"Retirar del catálogo":"Publicar plantilla o documento"}</h3><button disabled={busy} onClick={()=>{setUpload(false);setTarget(null);}} aria-label="Cerrar"><X/></button></header><form onSubmit={e=>{e.preventDefault();void(target?archive():publish());}}>{target?<><strong>{target.title}</strong><p>{target.archived?"Volverá a estar disponible para su departamento.":"Dejará de aparecer en el catálogo activo, pero el archivo se conservará."}</p></>:<><label className="mc-upload"><Upload/><strong>{file?.name||"Seleccionar PDF"}</strong><span>Hasta 10 MB. El archivo se conserva tal como lo subes.</span><input autoFocus required type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label>Título<input required minLength={3} maxLength={160} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Categoría<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{Object.entries(categories).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Disponible para<select value={draft.department} onChange={e=>setDraft({...draft,department:e.target.value})}><option value="ALL">Todos los departamentos</option>{Object.entries(departmentLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Descripción<textarea maxLength={2000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label></>}{error&&<p className="mw-error" role="alert">{error}</p>}<div className="mw-toolbar"><button type="button" disabled={busy} onClick={()=>{setUpload(false);setTarget(null);}}>Cancelar</button><button autoFocus={!!target} className="primary" disabled={busy}>{busy?"Guardando…":target?"Confirmar":"Publicar PDF"}</button></div></form></section></div>}
 </section>;
}
