import {ArrowDownLeft,ArrowRight,ArrowUpRight,Boxes,ClipboardList,FileText,FolderOpen,History,Monitor,PackageCheck,RefreshCw,Send,UsersRound,Warehouse,Wrench,AlertCircle} from "lucide-react";
import type {MaintenanceDocumentMovement} from "./maintenanceDocumentPdf";
import {departmentLabels,formatDocumentTime} from "./maintenanceDocumentPdf";
import {deviceTimestamp} from "@/lib/display";
type Area="WAREHOUSE"|"WORKSHOP";
type View="dashboard"|"inventory"|"history"|"procurement";
type Panel="requests"|"requirements"|"templates"|"files";
const labels:Record<string,string>={ENTRY:"Entrada",EXIT:"Salida",REPAIR:"Reparación",REPLACEMENT:"Reemplazo",COMPONENT_REPLACEMENT:"Componente",TRANSFER_TO_WORKSHOP:"Envío a Taller",DISCHARGE:"Descargo",NEW_DELIVERY:"Entrega",DAMAGED_RETURN:"Recepción",REQUEST:"Solicitud"};
export default function MaintenanceOverview({area,movements,loading,error,onRefresh,onDepartment,onPanel,onDocument,pendingOrders,departmentScope}:{area:Area;movements:MaintenanceDocumentMovement[];loading:boolean;error:string;onRefresh:()=>void;onDepartment:(department:string,view:View)=>void;onPanel:(panel:Panel)=>void;onDocument:(item:MaintenanceDocumentMovement)=>void;pendingOrders:number;departmentScope?:string[]}){
 const warehouse=area==="WAREHOUSE";
 const workshopAllowed=(m:MaintenanceDocumentMovement)=>m.department==="TECHNOLOGY"||(m.department==="GENERAL_SERVICES"&&/INVERSOR|INVERTER/i.test(m.equipmentType));
 const rows=movements.filter(m=>(m.operationalArea===area||(!warehouse&&m.movementType==="TRANSFER_TO_WORKSHOP"))&&(warehouse||workshopAllowed(m))&&(!departmentScope?.length||departmentScope.includes(m.department)));
 const latest=new Map<string,MaintenanceDocumentMovement>();
 for(const item of [...rows].sort((a,b)=>deviceTimestamp(b.createdAt)-deviceTimestamp(a.createdAt))){const key=item.serialNumber?.trim().toUpperCase();if(key&&!latest.has(key))latest.set(key,item);}
 const active=latest.size;
 const pending=warehouse?pendingOrders:[...latest.values()].filter(m=>m.movementType==="TRANSFER_TO_WORKSHOP").length;
  const departments=(warehouse?["TECHNOLOGY","GENERAL_SERVICES"]:["TECHNOLOGY","GENERAL_SERVICES"]).filter(code=>!departmentScope?.length||departmentScope.includes(code));
 const descriptions:Record<string,string>={TECHNOLOGY:"Equipos tecnológicos y periféricos",GENERAL_SERVICES:warehouse?"Herramientas, mobiliario y mantenimiento":"Exclusivo para inversores",HUMAN_RESOURCES:"Recursos y equipos del personal"};
 const recent=[...rows].sort((a,b)=>deviceTimestamp(b.createdAt)-deviceTimestamp(a.createdAt)).slice(0,5);
 const metrics=[{label:warehouse?"Activos identificados":"Equipos identificados",value:active,detail:"Seriales únicos registrados",icon:Boxes},{label:warehouse?"Órdenes abiertas":"Por intervenir",value:pending,detail:warehouse?"Pendientes de recepción":"Enviados desde Almacén",icon:ClipboardList},{label:warehouse?"Salidas registradas":"Intervenciones",value:rows.filter(m=>warehouse?["EXIT","NEW_DELIVERY","TRANSFER_TO_WORKSHOP"].includes(m.movementType):["REPAIR","REPLACEMENT","COMPONENT_REPLACEMENT"].includes(m.movementType)).length,detail:warehouse?"Entregas y transferencias":"Reparaciones y reemplazos",icon:warehouse?ArrowUpRight:Wrench},{label:"Formularios",value:rows.length,detail:"Historial con PDF y QR",icon:FileText}];
 return <section className={"ops-overview "+(warehouse?"warehouse":"workshop")} aria-label={warehouse?"Resumen de Almacén":"Resumen de Taller"}>
  <header className="ops-heading"><div><span className="ops-eyebrow">OFICINA VIRTUAL / OPERACIONES</span><h1>{warehouse?"Almacén central":"Taller técnico"}<span>{warehouse?<Warehouse/>:<Wrench/>}</span></h1><p>{warehouse?"Cada equipo, cada entrega. Todo bajo control.":"De la recepción a la reparación, en un solo lugar."}</p></div><button className="ops-secondary" disabled={loading} onClick={onRefresh}><RefreshCw className={loading?"spin":""}/>{loading?"Actualizando…":"Actualizar"}</button></header>
  {error&&<div className="ops-alert" role="alert"><AlertCircle/><span><strong>No se pudo actualizar la información</strong>{error}</span><button onClick={onRefresh}>Reintentar</button></div>}
  <div className="ops-metrics">{metrics.map(({label,value,detail,icon:Icon},i)=><article key={label}><div><span>{label}</span><Icon/></div><strong>{loading||error?"—":value.toLocaleString("es-DO")}</strong><small><i className={"tone-"+i}/>{detail}</small></article>)}</div>
  <div className="ops-workspace-grid"><div className="ops-main-column">
   <section className="ops-departments" id="maintenance-inventory-destination"><header className="ops-section-heading"><div><span className="ops-eyebrow">{warehouse?"ALMACÉN CENTRAL · CONTROL POR DEPARTAMENTO":"TALLERES INDEPENDIENTES · CONTROL POR DEPARTAMENTO"}</span><h2>Selecciona el departamento</h2><p>{warehouse?"Consulta existencias, registra movimientos y gestiona compras.":"Tecnología y Servicios Generales operan talleres separados; Servicios Generales recibe únicamente inversores."}</p></div><span className="ops-count">{departments.length.toString().padStart(2,"0")} áreas</span></header><div className="ops-department-list">{departments.map((code,i)=>{const count=rows.filter(m=>m.department===code).length;const Icon=code==="TECHNOLOGY"?Monitor:code==="GENERAL_SERVICES"?Wrench:UsersRound;return <article key={code}><button className="ops-department-open" onClick={()=>onDepartment(code,"dashboard")} aria-label={"Abrir "+departmentLabels[code]}><span className={"ops-dept-icon dept-"+i}><Icon/></span><span><strong>{departmentLabels[code]}</strong><small>{descriptions[code]}</small></span><ArrowUpRight/></button><footer><span>{loading||error?"Información pendiente":count+" movimientos registrados"}</span><button onClick={()=>onDepartment(code,"inventory")}>{warehouse?"Ver inventario":"Ver equipos"}<ArrowRight/></button></footer></article>;})}</div></section>
   <section className="ops-activity"><header className="ops-section-heading"><div><span className="ops-eyebrow">TRAZABILIDAD</span><h2>Últimos movimientos</h2></div><span className="ops-count"><History/>Recientes</span></header>{recent.length?<div className="ops-activity-table"><table><thead><tr><th>Equipo / documento</th><th>Departamento</th><th>Movimiento</th><th>Fecha</th><th><span className="ops-sr-only">Ver documento</span></th></tr></thead><tbody>{recent.map(item=><tr key={item.id}><td><strong>{item.equipmentType}</strong><small>{item.documentNumber}</small></td><td>{departmentLabels[item.department]||item.department}</td><td><span className={"ops-status "+(item.movementType==="ENTRY"?"incoming":item.movementType==="REPAIR"?"repair":"")}>{labels[item.movementType]||item.movementType}</span></td><td>{formatDocumentTime(item.createdAt).split(",")[0]}</td><td><button aria-label={"Ver formulario "+item.documentNumber} onClick={()=>onDocument(item)}><ArrowUpRight/></button></td></tr>)}</tbody></table></div>:<div className="ops-empty"><ArrowDownLeft/><strong>{loading?"Cargando movimientos…":error?"Información no disponible":"Tu próximo movimiento comienza aquí"}</strong><p>{error?"Reintenta la conexión para consultar el historial.":"Selecciona un departamento para registrar una entrada o consultar sus equipos."}</p></div>}</section>
  </div><aside className="ops-side-column"><section className="ops-actions"><header><span className="ops-eyebrow">A UN CLIC</span><h2>Centro de trabajo</h2></header>{(warehouse?[{key:"requests" as Panel,title:"Comunicaciones de departamentos",detail:"Recepción y seguimiento",icon:Send},{key:"requirements" as Panel,title:"Requerimientos",detail:"Revisar y autorizar",icon:ClipboardList}]:[]).concat([{key:"templates" as Panel,title:"Mis plantillas",detail:"Formularios, firma y sello",icon:FileText},{key:"files" as Panel,title:"Archivos",detail:"Biblioteca y documentos",icon:FolderOpen}]).map(({key,title,detail,icon:Icon})=><button key={key} onClick={()=>onPanel(key)}><span><Icon/></span><span><strong>{title}</strong><small>{detail}</small></span><ArrowRight/></button>)}</section><section className="ops-guide"><span className="ops-guide-icon"><PackageCheck/></span><span className="ops-eyebrow">UN PROCESO, TODO CONECTADO</span><h3>{warehouse?"Del almacén a su destino":"Listo para volver a operar"}</h3><p>{warehouse?"Registra cada entrega y conserva la constancia de quién entrega y quién recibe.":"Documenta el diagnóstico, registra la reparación y entrega con una constancia."}</p><ol>{(warehouse?["Selecciona el departamento","Registra el movimiento","Completa firma y recibido"]:["Recibe e identifica el equipo","Registra la intervención","Entrega y firma el formulario"]).map((step,i)=><li key={step}><b>0{i+1}</b>{step}</li>)}</ol><button onClick={()=>onPanel("templates")}>Plantillas y archivos institucionales<ArrowUpRight/></button></section></aside></div>
 </section>;
}

