import {useEffect,useRef,useState} from "react";
import {Download,X} from "lucide-react";
import InstitutionalBrand from "./InstitutionalBrand";
export default function PdfFilePreview({url,title,onClose}:{url:string;title:string;onClose:()=>void}){
 const [zoom,setZoom]=useState(100); const [page,setPage]=useState(1),[count,setCount]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState("");const canvas=useRef<HTMLCanvasElement>(null),close=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow="hidden";close.current?.focus();return()=>{document.body.style.overflow=overflow;previous?.focus();};},[]);
 useEffect(()=>{let cancelled=false;let destroy:(()=>void)|undefined;setLoading(true);setError("");(async()=>{const response=await fetch(url,{credentials:"same-origin",cache:"no-store"});if(!response.ok)throw new Error("No fue posible cargar el archivo. Revisa tu sesión o actualiza la biblioteca.");const bytes=await response.arrayBuffer();if(cancelled)return;const path="/vendor/pdfjs/pdf.mjs",pdfjs=await import(/* @vite-ignore */ path);pdfjs.GlobalWorkerOptions.workerSrc="/vendor/pdfjs/pdf.worker.mjs";pdfjs.setVerbosityLevel?.(pdfjs.VerbosityLevel?.ERRORS??0);const task=pdfjs.getDocument({data:new Uint8Array(bytes),isEvalSupported:false});destroy=()=>{void task.destroy();};const doc=await task.promise;if(cancelled){destroy();return;}setCount(doc.numPages);const pdfPage=await doc.getPage(Math.min(page,doc.numPages)),viewport=pdfPage.getViewport({scale:1.3});if(cancelled||!canvas.current)return;canvas.current.width=viewport.width;canvas.current.height=viewport.height;await pdfPage.render({canvas:canvas.current,canvasContext:canvas.current.getContext("2d"),viewport}).promise;if(!cancelled)setLoading(false);})().catch(e=>{if(!cancelled){setError(e.message);setLoading(false);}});return()=>{cancelled=true;destroy?.();};},[url,page]);
 return <div className="mw-overlay"><section className="mc-pdf-panel" role="dialog" aria-modal="true" aria-labelledby="file-preview-title" onKeyDown={e=>{if(e.key==="Escape")onClose();if(e.key==="Tab"){const nodes=e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),a[href]'),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><header><div><InstitutionalBrand/><h3 id="file-preview-title">{title}</h3></div><button ref={close} onClick={onClose} aria-label="Cerrar vista previa"><X/></button></header>{loading&&<p role="status">Preparando documento…</p>}{error&&<p className="mw-error" role="alert">{error}</p>}<div className="mw-preview-controls"><strong>Vista de plantilla · PDF</strong><label>Zoom <select aria-label="Zoom de la plantilla" value={zoom} onChange={e=>setZoom(Number(e.target.value))}><option value={100}>Ajustar a pantalla</option><option value={125}>125 %</option><option value={150}>150 %</option></select></label><span>Página {page} de {count}</span></div><div className="mc-pdf-sheet"><canvas style={{width:`${zoom}%`,maxWidth:zoom===100?undefined:"none"}} ref={canvas} aria-label={`Página ${page} del PDF`}/></div><footer><button disabled={page===1||loading} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>{page} / {count}</span><button disabled={page===count||loading} onClick={()=>setPage(p=>p+1)}>Siguiente</button><a href={url} download><Download/> Descargar PDF</a></footer></section></div>;
}

