import {useCallback,useEffect,useState} from "react";
import {Check,Plus,RefreshCw,Send,X,Eye,Grid2X2,List,Inbox,Search,FolderOpen,ArrowRight} from "lucide-react";
import type {PortalSession} from "@/lib/session";
import {maintenanceApi} from "./maintenanceApi";
import {departmentLabels,formatDocumentTime} from "./maintenanceDocumentPdf";
import "./maintenanceWorkflow.css";
import InstitutionalBrand from "./InstitutionalBrand";
type Entry={id:string;department:string;productName:string;quantity?:number;quantityRequested?:number;notes?:string;status:string;createdAt:string;createdByName?:string;requestedByName?:string;requisitionNumber?:string;decidedByName?:string;decidedByLogin?:string;decidedAt?:string;decisionReason?:string};
const labels:Record<string,string>={PENDING:"Pendiente de autorización",APPROVED:"Autorizado",REJECTED:"Rechazado",ORDERED:"En compra",PARTIAL:"Entrega parcial",FULFILLED:"Completado",CANCELLED:"Cancelado",SENT:"Enviada al departamento"};
export default function WarehouseRequests({kind,session,department,onChanged}:{kind:"requests"|"requirements";session:PortalSession;department:string;onBack:()=>void;onChanged:()=>void}){
 const warehouse=session.supportTeam==="WAREHOUSE"||session.role==="Administrator",requirements=kind==="requirements";
 const [board,setBoard]=useState<{requests:Entry[];requirements:Entry[]}>({requests:[],requirements:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[decision,setDecision]=useState<{entry:Entry;status:string}|null>(null),[reason,setReason]=useState(""),[filter,setFilter]=useState(department),[query,setQuery]=useState("");
 const [statusFilter,setStatusFilter]=useState("ALL"),[view,setView]=useState("list"),[sort,setSort]=useState("recent"),[selected,setSelected]=useState<Entry|null>(null),[page,setPage]=useState(1);
 const [draft,setDraft]=useState({department:department||session.supportDepartment||"",productName:"",quantity:1,notes:"",priority:"MEDIUM"});
 const load=useCallback(async()=>{setLoading(true);try{const data=await maintenanceApi<{requests?:Entry[];requirements?:Entry[]}>("/api/maintenance/request-board");setBoard({requests:data.requests||[],requirements:data.requirements||[]});setError("");}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();const refresh=()=>{void load();};window.addEventListener("support-live-refresh",refresh);return()=>window.removeEventListener("support-live-refresh",refresh);},[load]);
 useEffect(()=>{const scoped=department||(!warehouse?session.supportDepartment||"":"");setFilter(scoped);setDraft(d=>({...d,department:scoped||d.department}));},[department,session.supportDepartment,warehouse]);
 const channelItems=requirements?board.requirements:board.requests;
 const scopedDepartment=department||(!warehouse?session.supportDepartment||"":"");
 const scopedItems=channelItems.filter(item=>!scopedDepartment||item.department===scopedDepartment);
  const warehouseDepartments=Object.entries(departmentLabels).filter(([key])=>key==="TECHNOLOGY"||key==="GENERAL_SERVICES");
  const selectableDepartments=warehouse&&!scopedDepartment?warehouseDepartments:warehouse&&scopedDepartment?warehouseDepartments.filter(([key])=>key===scopedDepartment):Object.entries(departmentLabels).filter(([key])=>key===(scopedDepartment||session.supportDepartment));
 const items=scopedItems.filter(item=>(!filter||item.department===filter)&&`${item.productName} ${item.requisitionNumber||""} ${item.requestedByName||item.createdByName||""}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())&&(statusFilter==="ALL"||item.status===statusFilter)).sort((a,b)=>sort==="name"?a.productName.localeCompare(b.productName,"es"):(sort==="oldest"?a.createdAt.localeCompare(b.createdAt):b.createdAt.localeCompare(a.createdAt)));
 useEffect(()=>setPage(1),[filter,query,statusFilter,sort]);
 const pages=Math.max(1,Math.ceil(items.length/12)),currentPage=Math.min(page,pages);
 async function send(){setBusy(true);setError("");try{await maintenanceApi(requirements?"/api/maintenance/requisitions":"/api/maintenance/department-requests","POST",draft);setOpen(false);setDraft(d=>({...d,productName:"",quantity:1,notes:""}));setNotice(requirements?"Requerimiento enviado a Almacén. Queda pendiente de autorización.":"Solicitud enviada al departamento seleccionado.");await load();onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function decide(){if(!decision)return;setBusy(true);setError("");try{await maintenanceApi(`/api/maintenance/requisitions/${decision.entry.id}/decision`,"POST",{status:decision.status,reason});setDecision(null);setReason("");setNotice("Decisión guardada con tu cuenta, fecha y motivo.");await load();onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="mw-board mc-communications-board"><header className="mc-page-heading"><div><small>{requirements?"EQUIPOS SOLICITADOS A ALMACÉN":"COMUNICACIONES DE DEPARTAMENTOS"}</small><h3>{requirements?"Requerimientos":"Comunicaciones"}</h3><p>{requirements?"Revisa los equipos solicitados y su autorización.":"Consulta las comunicaciones recibidas de Tecnología y Servicios Generales."}</p></div><div className="mw-toolbar"><button disabled={loading||busy} onClick={()=>void load()}><RefreshCw/> Actualizar</button>{(requirements||warehouse)&&<button className="primary" disabled={busy} onClick={()=>{setOpen(true);setError("");}}><Plus/> {requirements?"Nuevo requerimiento":"Nueva comunicación"}</button>}</div></header>
 <div className="mc-summary"><article><Inbox/><span><strong>{scopedItems.length}</strong><small>{requirements?"Requerimientos registrados":"Solicitudes enviadas"}</small></span></article><article><Check/><span><strong>{scopedItems.filter(i=>requirements?["APPROVED","ORDERED","PARTIAL","FULFILLED"].includes(i.status):i.status==="SENT").length}</strong><small>{requirements?"Autorizados / en gestión":"Enviadas al departamento"}</small></span></article>{requirements&&<article><Inbox/><span><strong>{scopedItems.filter(i=>i.status==="PENDING").length}</strong><small>Pendientes de decisión</small></span></article>}</div>
 {requirements&&warehouse&&<section className="mc-department-folders" aria-label="Carpetas de requerimientos por departamento"><header><div><small>{scopedDepartment?"ORGANIZACIÓN DEL DEPARTAMENTO":"ORGANIZACIÓN DE ALMACÉN"}</small><h4>{scopedDepartment?`Requerimientos de ${departmentLabels[scopedDepartment]||scopedDepartment}`:"Requerimientos por departamento"}</h4><p>{scopedDepartment?"Aquí solo aparecen los equipos solicitados por este departamento.":"Abre una carpeta para consultar solamente los requerimientos enviados por esa área."}</p></div>{!scopedDepartment&&<button className={!filter?"active":""} onClick={()=>setFilter("")}><Grid2X2/> Ver todos</button>}</header><div>{selectableDepartments.map(([key,label])=>{const count=scopedItems.filter(item=>item.department===key).length;const pending=scopedItems.filter(item=>item.department===key&&item.status==="PENDING").length;return <button key={key} className={filter===key?"active":""} onClick={()=>setFilter(key)}><span><FolderOpen/></span><small>DEPARTAMENTO</small><strong>{label}</strong><em>{count} requerimientos · {pending} pendientes</em><b>Abrir carpeta <ArrowRight/></b></button>})}</div></section>}
 <div className="mc-searchbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar equipo, número o responsable…" aria-label="Buscar comunicaciones"/></label><select aria-label="Departamento" value={filter} onChange={e=>setFilter(e.target.value)}>{warehouse&&!scopedDepartment&&<option value="">Todos los departamentos</option>}{selectableDepartments.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><select aria-label="Ordenar comunicaciones" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Más recientes</option><option value="oldest">Más antiguas</option><option value="name">Equipo A–Z</option></select><div className="mc-view-switch"><button aria-label="Vista de lista" aria-pressed={view==="list"} onClick={()=>setView("list")}><List/></button><button aria-label="Vista de tarjetas" aria-pressed={view==="cards"} onClick={()=>setView("cards")}><Grid2X2/></button></div></div>
 {error&&<p className="mw-error" role="alert">{error}</p>}{notice&&<p className="mw-notice" role="status">{notice}</p>}
 <div className="mc-catalog-layout"><main><div className="mc-results"><strong>{statusFilter==="ALL"?"Todas las comunicaciones":labels[statusFilter]}</strong><span>{items.length} registros</span></div>
 {loading&&!items.length?<p role="status">Cargando…</p>:<div className={`mw-request-grid mc-request-collection ${view}`}>{items.slice((currentPage-1)*12,currentPage*12).map(item=><article key={item.id}><div className="mc-request-title"><span className={`mw-status ${item.status.toLowerCase()}`}>{labels[item.status]||item.status}</span><small>{departmentLabels[item.department]}</small><h3>{item.productName}</h3><p>{item.requisitionNumber||`SOL-${item.id.slice(0,8).toUpperCase()}`} · {item.quantityRequested??item.quantity} unidad(es)</p></div><p className="mc-excerpt">{item.notes||"Sin notas adicionales"}</p><footer><strong>{item.requestedByName||item.createdByName}</strong><time>{formatDocumentTime(item.createdAt)}</time>{item.decidedAt&&<small>{labels[item.status]} por {item.decidedByName}</small>}</footer><div className="mw-toolbar mc-row-actions"><button onClick={()=>setSelected(item)}><Eye/> Leer comunicación</button>{requirements&&warehouse&&item.status==="PENDING"&&<><button className="primary" disabled={busy} onClick={()=>{setReason("");setDecision({entry:item,status:"APPROVED"});}}><Check/> Autorizar</button><button className="danger" disabled={busy} onClick={()=>{setReason("");setDecision({entry:item,status:"REJECTED"});}}><X/> Rechazar</button></>}</div></article>)}{!items.length&&<div className="mc-empty"><Inbox/><h4>Sin comunicaciones con estos filtros</h4><p>Prueba otro departamento, estado o búsqueda.</p></div>}</div>}
 {pages>1&&<div className="mc-pagination"><button disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Anterior</button><span>Página {currentPage} de {pages}</span><button disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Siguiente</button></div>}</main>
  <aside><section className="mc-side-panel"><h4>{requirements?"Estado del requerimiento":warehouse?"Comunicaciones de departamentos":"Bandeja de comunicaciones"}</h4><button className={statusFilter==="ALL"?"active":""} onClick={()=>setStatusFilter("ALL")}><Inbox/> Todos<b>{scopedItems.length}</b></button>{(requirements?["PENDING","APPROVED","REJECTED","ORDERED","PARTIAL","FULFILLED","CANCELLED"]:["SENT"]).map(status=><button key={status} className={statusFilter===status?"active":""} onClick={()=>setStatusFilter(status)}>{labels[status]}<b>{scopedItems.filter(item=>item.status===status).length}</b></button>)}</section><section className="mc-help-card"><Send/><h4>{requirements?"Decisiones trazables":"Destino claro"}</h4><p>{requirements?"Almacén autoriza o rechaza con un motivo. La entrega se registra después en su formulario de inventario.":"Cada comunicación se muestra al departamento relacionado, junto con su fecha y responsable."}</p></section></aside></div>
 {selected&&<div className="mw-overlay"><section className="mc-letter" role="dialog" aria-modal="true" aria-labelledby="communication-title" onKeyDown={e=>{if(e.key==="Escape")setSelected(null);if(e.key==="Tab"){const nodes=e.currentTarget.querySelectorAll<HTMLElement>("button"),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><header><InstitutionalBrand/><button autoFocus onClick={()=>setSelected(null)} aria-label="Cerrar comunicación"><X/></button></header><small>{requirements?"REQUERIMIENTO A ALMACÉN":"SOLICITUD AL DEPARTAMENTO"} · {selected.requisitionNumber||`SOL-${selected.id.slice(0,8).toUpperCase()}`}</small><h3 id="communication-title">{selected.productName}</h3><dl><div><dt>Departamento</dt><dd>{departmentLabels[selected.department]}</dd></div><div><dt>Cantidad</dt><dd>{selected.quantityRequested??selected.quantity}</dd></div><div><dt>Remitente</dt><dd>{selected.requestedByName||selected.createdByName}</dd></div><div><dt>Fecha</dt><dd>{formatDocumentTime(selected.createdAt)}</dd></div></dl><p className="mc-letter-body">{selected.notes||"Sin detalles adicionales."}</p><span className={`mw-status ${selected.status.toLowerCase()}`}>{labels[selected.status]}</span>{selected.decidedAt&&<div className="mw-decision"><strong>{selected.decidedByName} · {selected.decidedByLogin}</strong><time>{formatDocumentTime(selected.decidedAt)}</time><p>{selected.decisionReason}</p></div>}<footer><button onClick={()=>setSelected(null)}>Cerrar lectura</button></footer></section></div>}
 {(open||decision)&&<div className="mw-overlay"><section className="mw-form-panel" role="dialog" aria-modal="true" aria-labelledby="request-title" onKeyDown={e=>{if(e.key==="Escape"&&!busy){setOpen(false);setDecision(null);}if(e.key==="Tab"){const nodes=e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea');const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><header><h3 id="request-title">{decision?`${decision.status==="APPROVED"?"Autorizar":"Rechazar"} requerimiento`:requirements?"Solicitar equipos a Almacén":"Enviar solicitud a un departamento"}</h3><button disabled={busy} onClick={()=>{setOpen(false);setDecision(null);}} aria-label="Cerrar"><X/></button></header><form onSubmit={e=>{e.preventDefault();void(decision?decide():send());}}>
  {decision?<><p>{decision.entry.productName} · {decision.entry.quantityRequested} unidad(es)</p><label>Motivo de la decisión<textarea autoFocus required minLength={5} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explica la autorización o el rechazo"/></label><small>Autorizar no registra una entrega ni modifica el inventario. El despacho se registra con su formulario correspondiente.</small></>:<><label>Departamento<select autoFocus required disabled={!warehouse} value={draft.department} onChange={e=>setDraft({...draft,department:e.target.value})}><option value="">Seleccionar departamento</option>{selectableDepartments.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Equipo / artículo<input required maxLength={160} value={draft.productName} onChange={e=>setDraft({...draft,productName:e.target.value})}/></label><label>Cantidad<input required type="number" min={1} max={100000} step={1} value={draft.quantity} onChange={e=>setDraft({...draft,quantity:Number(e.target.value)})}/></label>{requirements&&<label>Prioridad<select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value})}><option value="LOW">Baja</option><option value="MEDIUM">Media</option><option value="HIGH">Alta</option><option value="CRITICAL">Crítica</option></select></label>}<label>Motivo / detalles<textarea required maxLength={2000} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label></>}
 {error&&<p className="mw-error" role="alert">{error}</p>}<div className="mw-toolbar"><button type="button" disabled={busy} onClick={()=>{setOpen(false);setDecision(null);}}>Cancelar</button><button type="submit" className="primary" disabled={busy}><Send/>{busy?"Guardando…":decision?"Confirmar decisión":"Enviar"}</button></div></form></section></div>}
 </section>;
}
