import {useCallback,useEffect,useMemo,useState} from "react";
import {CheckCircle2,Download,Eye,FileText,FolderOpen,Grid2X2,Inbox,List,LoaderCircle,Printer,RefreshCw,Search,Stamp} from "lucide-react";
import type {PortalSession} from "@/lib/session";
import InstitutionalDocumentDetail from "./InstitutionalDocumentDetail";
import type {DocumentDetail,DocumentItem} from "./DocumentSystemModule";

type PdfRequest=DocumentItem&{isRecipient?:boolean;ownerDisplayName?:string};
const names:Record<string,string>={pending:"Pendiente",received:"Recibida",approved:"Autorizada",rejected:"Rechazada",correction_requested:"Corrección solicitada"};
const departments=["Tecnología","Servicios Generales"];

export default function WarehousePdfRequests({session,department}:{session:PortalSession;department:string}){
  const warehouse=session.supportTeam==="WAREHOUSE"||(session.role==="Administrator"&&!department);
  const [items,setItems]=useState<PdfRequest[]>([]),[detail,setDetail]=useState<DocumentDetail|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [query,setQuery]=useState(""),[departmentFilter,setDepartmentFilter]=useState(department==='TECHNOLOGY'?"Tecnología":department==='GENERAL_SERVICES'?"Servicios Generales":""),[status,setStatus]=useState("pending"),[view,setView]=useState<"list"|"cards">("list");
  const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/institutional-documents?area=communications&channel=requirements&view=all",{credentials:"same-origin",cache:"no-store"});if(!response.ok)throw new Error("No se pudieron cargar las solicitudes PDF.");setItems(await response.json());setError("")}catch(reason){setError((reason as Error).message)}finally{setLoading(false)}},[]);
  useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener("support-live-refresh",refresh);return()=>window.removeEventListener("support-live-refresh",refresh)},[load]);
  const visible=useMemo(()=>items.filter(item=>{const matchesStatus=status==="all"||(status==="pending"?["pending","correction_requested"].includes(item.status):item.status===status);return (!departmentFilter||item.department===departmentFilter)&&matchesStatus&&`${item.title} ${item.description||""} ${item.ownerDisplayName||item.ownerUserName}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())}),[items,departmentFilter,status,query]);
  const count=(value:string)=>value==="pending"?items.filter(item=>["pending","correction_requested"].includes(item.status)).length:value==="all"?items.length:items.filter(item=>item.status===value).length;
  async function open(item:PdfRequest){const response=await fetch(`/api/institutional-documents/${item.id}`,{credentials:"same-origin",cache:"no-store"});if(!response.ok){setError("No se pudo abrir la solicitud PDF.");return}setDetail(await response.json())}
  async function refreshDetail(){if(!detail)return;await load();const response=await fetch(`/api/institutional-documents/${detail.id}`,{credentials:"same-origin",cache:"no-store"});if(response.ok)setDetail(await response.json())}
  async function receive(item:PdfRequest){setBusy(true);setError("");try{const response=await fetch(`/api/institutional-documents/${item.id}/actions/receive`,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({sealX:73,sealY:71})});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.message||"No se pudo registrar la recepción.")}await load();setStatus("received")}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  if(!warehouse)return null;
  if(detail)return <InstitutionalDocumentDetail item={detail} onBack={()=>setDetail(null)} onChanged={refreshDetail}/>;
  return <section className="warehouse-pdf-management" aria-labelledby="warehouse-pdf-title">
    <header className="mc-page-heading"><div><small>ALMACÉN · RECEPCIÓN DOCUMENTAL</small><h3 id="warehouse-pdf-title">Solicitudes PDF</h3><p>Recibe los formularios enviados por Tecnología y Servicios Generales. Después de recibirlos pasan a Recibidos para ser autorizados o rechazados.</p></div><button type="button" disabled={loading} onClick={()=>void load()}>{loading?<LoaderCircle className="spin"/>:<RefreshCw/>}Actualizar</button></header>
    <div className="mc-summary"><article><FileText/><span><strong>{items.length}</strong><small>Solicitudes registradas</small></span></article><article><Inbox/><span><strong>{count("pending")}</strong><small>Pendientes de recibir</small></span></article><article><CheckCircle2/><span><strong>{count("received")}</strong><small>Recibidas para decisión</small></span></article></div>
    <section className="mc-department-folders"><header><div><small>ORGANIZACIÓN DE ALMACÉN</small><h4>Solicitudes por departamento</h4><p>Abre una carpeta para revisar únicamente los formularios enviados por esa área.</p></div><button className={!departmentFilter?"active":""} onClick={()=>setDepartmentFilter("")}><Grid2X2/>Ver todos</button></header><div>{departments.map(name=>{const scoped=items.filter(item=>item.department===name);return <button key={name} className={departmentFilter===name?"active":""} onClick={()=>setDepartmentFilter(name)}><span><FolderOpen/></span><small>DEPARTAMENTO</small><strong>{name}</strong><em>{scoped.length} solicitudes · {scoped.filter(item=>["pending","correction_requested"].includes(item.status)).length} pendientes</em><b>Abrir carpeta</b></button>})}</div></section>
    <div className="mc-searchbar"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar formulario, agencia o remitente…"/></label><select value={departmentFilter} onChange={event=>setDepartmentFilter(event.target.value)}><option value="">Todos los departamentos</option>{departments.map(name=><option key={name}>{name}</option>)}</select><div className="mc-view-switch"><button aria-label="Vista de lista" aria-pressed={view==="list"} onClick={()=>setView("list")}><List/></button><button aria-label="Vista de tarjetas" aria-pressed={view==="cards"} onClick={()=>setView("cards")}><Grid2X2/></button></div></div>
    {error&&<p className="mw-error" role="alert">{error}</p>}
    <div className="mc-catalog-layout"><main><div className="mc-results"><strong>{status==="all"?"Todas las solicitudes":names[status]||status}</strong><span>{visible.length} formularios</span></div><div className={`mw-request-grid mc-request-collection warehouse-pdf-list ${view}`}>{visible.map(item=><article key={item.id}><div className="mc-request-title"><span className={`mw-status ${item.status}`}>{names[item.status]||item.status}</span><small>{item.department}</small><h3>{item.title}</h3><p>{item.originalFileName} · {(item.size/1024).toFixed(1)} KB</p></div><p className="mc-excerpt">{item.description||"Solicitud PDF institucional"}</p><footer><strong>{item.ownerDisplayName||item.ownerUserName}</strong><time>{new Date(item.createdUtc).toLocaleString("es-DO",{timeZone:"America/Santo_Domingo"})}</time></footer><div className="mw-toolbar mc-row-actions"><button onClick={()=>void open(item)}><Eye/>Ver documento</button><a href={`/api/institutional-documents/${item.id}/download`}><Download/>Descargar</a><button onClick={()=>window.open(`/api/institutional-documents/${item.id}/preview`,"_blank","noopener,noreferrer")}><Printer/>Imprimir</button>{["pending","correction_requested"].includes(item.status)&&item.isRecipient&&<button className="primary" disabled={busy} onClick={()=>void receive(item)}><Stamp/>Marcar recibido</button>}</div></article>)}{!loading&&!visible.length&&<div className="mc-empty"><Inbox/><h4>No hay solicitudes PDF con estos filtros</h4><p>Los formularios enviados a Almacén aparecerán aquí.</p></div>}</div></main><aside><section className="mc-side-panel"><h4>Estado de la solicitud</h4>{[["all","Todas"],["pending","Pendientes"],["received","Recibidas"],["approved","Autorizadas"],["rejected","Rechazadas"]].map(([value,label])=><button key={value} className={status===value?"active":""} onClick={()=>setStatus(value)}><Inbox/>{label}<b>{count(value)}</b></button>)}</section><section className="mc-help-card"><Stamp/><h4>Recepción flexible</h4><p>Puedes descargar o imprimir el PDF sin firma ni sello. Al marcarlo recibido se identifica tu cuenta; después la firma es opcional y se habilita la decisión.</p></section></aside></div>
  </section>;
}
