import {readFileSync} from 'node:fs';
import {describe,it,expect} from 'vitest';
import {PDFDocument} from 'pdf-lib';
import {buildInstitutionalLetter,newLetterForm,parseLetterForm} from '../src/components/vite/institutionalLetterPdf';
import {buildReceiptCopy} from '../src/components/vite/institutionalReceiptPdf';
import type {DocumentDetail} from '../src/components/vite/DocumentSystemModule';
describe('módulo documental del ZIP integrado',()=>{
 it('preserva campos y pagina todo el contenido sin recortar párrafos',()=>{const form={...newLetterForm(),subject:'Solicitud de equipo',body:'Este párrafo se conserva completo.\n'.repeat(200)+'MARCADOR FINAL',signerName:'Persona de entrega'};const pdf=buildInstitutionalLetter(form);expect(pdf.getNumberOfPages()).toBeGreaterThan(3);expect(pdf.output()).toContain('MARCADOR FINAL');expect(pdf.output()).toContain('FIRMA DE QUIEN ENTREGA');expect(pdf.output()).toContain('FIRMA DE QUIEN RECIBE');expect(pdf.output()).not.toContain('ALCALD');});
 it('solo acepta textos conocidos al abrir una plantilla guardada',()=>{const form=parseLetterForm('{"subject":"Equipo","body":{},"__proto__":{"bad":true}}');expect(form.subject).toBe('Equipo');expect(form.body).toBe('');expect(({} as any).bad).toBeUndefined()});
 it('el PDF sellado conserva original, tiene QR, anexo y ubicación de firma',async()=>{const logo='data:image/png;base64,'+readFileSync('public/loto-real-logo-transparent.png').toString('base64');const base=buildInstitutionalLetter({...newLetterForm(),subject:'Prueba',body:'Documento de prueba'},'',logo);const original=new Uint8Array(base.output('arraybuffer'));const item={title:'Prueba',receivedUtc:'2026-09-03T16:00:00Z',receiverLogin:'demo.receptor',receiverDisplayName:'Receptor DEMO',receiptCode:'REAL-DEMO',verificationToken:'demo-token',sealX:98,sealY:98,status:'received',receiptSignature:logo} as DocumentDetail;const bytes=await buildReceiptCopy(original,item,logo,'https://example.invalid');const pdf=await PDFDocument.load(bytes);expect(pdf.getPageCount()).toBe(base.getNumberOfPages()+1);expect(pdf.getSubject()).toContain('SIGNATURE_PAGE=1');expect(original.length).toBe(base.output('arraybuffer').byteLength);expect(bytes.length).toBeGreaterThan(original.length)});
 it('protege descargas, firma y destinatarios desde el servidor',()=>{const server=readFileSync('api/InstitutionalDocumentEndpoints.cs','utf8'),store=readFileSync('api/InstitutionalDocumentStore.cs','utf8');expect(server).toContain('RequireAuthorization("PortalUser")');expect(server).toContain('10485760');expect(store).toContain('d.Accessible(a)');expect(store).toContain('IsolationLevel.Serializable');expect(store).toContain('UPDLOCK,HOLDLOCK');expect(store).toContain('if(!d.CanMove||d.ReceivedUtc is null)');expect(store).toContain('RecipientUserName is not null?RecipientUserName==a.Id');expect(server).not.toContain('AllowAnonymous');});
 it('no importa login demo, chat municipal ni almacenamiento local del ZIP',()=>{const ui=readFileSync('src/components/vite/DocumentSystemModule.tsx','utf8');expect(ui).not.toContain('/api/institutional-chat');expect(ui).not.toContain('localStorage');expect(ui).not.toContain('ASDE');expect(ui).toContain('Compartir');expect(ui).toContain('Papelera');expect(ui).toContain('Puede editar')});
});
