import {readFileSync} from "node:fs";
import {describe,it,expect} from "vitest";
import {renderToStaticMarkup} from "react-dom/server";
import MaintenanceCommunications from "../src/components/vite/MaintenanceCommunications";
import MaintenanceTemplates from '../src/components/vite/MaintenanceTemplates';
import type {PortalSession} from "../src/lib/session";
const session={role:"Technology",supportTeam:"WAREHOUSE",supportDepartment:"TECHNOLOGY"} as PortalSession;
describe("biblioteca y comunicaciones de mantenimiento",()=>{
 it("muestra a Almacén las comunicaciones de departamentos y los requerimientos",()=>{const html=renderToStaticMarkup(<MaintenanceCommunications view="templates" onNavigate={()=>{}} onBack={()=>{}} onChanged={()=>{}} session={session} department=""/>);for(const label of ["Comunicaciones de departamentos","Requerimientos","Mis plantillas","Archivos","Grupo Tejeda","Plantillas disponibles","Edición en vivo","Firma de quien entrega","Enviar"])expect(html).toContain(label);expect(html).not.toContain("Solicitudes recibidas");expect(html).not.toContain("Solicitudes a Almacén");expect(html).not.toContain("Ayuntamiento");expect(html).toContain('role="tablist"');expect(html).toContain('role="tabpanel"');});
 it("limita publicación al almacén o administrador también en la interfaz",()=>{const html=renderToStaticMarkup(<MaintenanceTemplates session={{...session,supportTeam:null}}/>);expect(html).not.toContain("Publicar PDF");expect(html).toContain("Conduce institucional - dos firmas");});
 it("muestra los requerimientos que Almacén debe autorizar",()=>{const html=renderToStaticMarkup(<MaintenanceCommunications view="requirements" onNavigate={()=>{}} onBack={()=>{}} onChanged={()=>{}} session={session} department=""/>);for(const label of ["Requerimientos","Nuevo requerimiento","Pendiente de autorización","Decisiones trazables"])expect(html).toContain(label);});
 it("abre las comunicaciones de Almacén primero por carpetas y después por estado",()=>{const html=renderToStaticMarkup(<MaintenanceCommunications view="requests" onNavigate={()=>{}} onBack={()=>{}} onChanged={()=>{}} session={session} department=""/>),source=readFileSync("src/components/vite/DocumentSystemModule.tsx","utf8"),styles=readFileSync("src/components/vite/maintenanceCommunications.css","utf8");for(const label of ["Comunicaciones de departamentos","Selecciona una carpeta","ALMACÉN · SOLICITUDES POR DEPARTAMENTO"])expect(html).toContain(label);expect(html).not.toContain('class="warehouse-inbox-status-tabs"');for(const label of ['label="Todas"','label="En tránsito"','label="Recibidas"','label="Rechazadas"'])expect(source).toContain(label);expect(source).toContain("['Tecnología','Servicios Generales','Recursos Humanos']");expect(styles).toContain('.mc-hub .warehouse-folder-grid>button');expect(styles).toContain('grid-template-areas:"icon eyebrow" "icon title" "icon count" "action action"');expect(styles).toContain('.mc-hub .warehouse-request-inbox .native-folder-toolbar');});
 it("organiza requerimientos por carpetas y valida la importación Excel",()=>{const requests=readFileSync("src/components/vite/WarehouseRequests.tsx","utf8"),center=readFileSync("src/components/vite/TicketCenter.tsx","utf8"),endpoint=readFileSync("api/InstitutionalDocumentEndpoints.cs","utf8");expect(requests).toContain("Requerimientos por departamento");expect(requests).toContain("Abrir carpeta");expect(center).toContain("Importar inventario desde Excel");expect(center).toContain('maintenanceInventoryImport.errors.length');expect(center).toContain("seriales duplicados fueron omitidos");expect(endpoint).toContain('"received"=>docs.Where(d=>d.Status=="received"||(d.Status=="approved"&&d.ReceivedUtc is not null))');});
 it("comprueba límites y autorización del servidor para publicar o retirar",()=>{const code=readFileSync("api/MaintenanceTemplateEndpoints.cs","utf8");expect(code).toContain('a.Role!="Administrator"&&a.Team!="WAREHOUSE"');expect(code).toContain("10485760");expect(code).toContain('SequenceEqual("%PDF-"u8)');expect(code).toContain('RequireAuthorization("PortalUser")');expect(readFileSync("api/DatabaseMaintenanceTemplates.cs","utf8")).toContain("is_archived=@archived");});
});
