import {readFileSync} from "node:fs";
import {describe,it,expect} from "vitest";
import {renderToStaticMarkup} from "react-dom/server";
import MaintenanceCommunications from "../src/components/vite/MaintenanceCommunications";
import MaintenanceTemplates from '../src/components/vite/MaintenanceTemplates';
import type {PortalSession} from "../src/lib/session";
const session={role:"Technology",supportTeam:"WAREHOUSE",supportDepartment:"TECHNOLOGY"} as PortalSession;
describe("biblioteca y comunicaciones de mantenimiento",()=>{
 it("muestra a Almacén las comunicaciones de departamentos y las solicitudes PDF",()=>{const html=renderToStaticMarkup(<MaintenanceCommunications view="templates" onNavigate={()=>{}} onBack={()=>{}} onChanged={()=>{}} session={session} department=""/>);for(const label of ["Comunicaciones de departamentos","Solicitudes PDF","Mis plantillas","Archivos","Grupo Tejeda","Plantillas disponibles","Edición en vivo","Firma de quien entrega","Enviar"])expect(html).toContain(label);expect(html).not.toContain("Solicitudes recibidas");expect(html).not.toContain("Solicitudes a Almacén");expect(html).not.toContain("Ayuntamiento");expect(html).toContain('role="tablist"');expect(html).toContain('role="tabpanel"');});
 it("limita publicación al almacén o administrador también en la interfaz",()=>{const html=renderToStaticMarkup(<MaintenanceTemplates session={{...session,supportTeam:null}}/>);expect(html).not.toContain("Publicar PDF");expect(html).toContain("Conduce institucional - dos firmas");});
 it("muestra los PDF con el formato de gestión, primero pendientes de recepción",()=>{const html=renderToStaticMarkup(<MaintenanceCommunications view="requirements" onNavigate={()=>{}} onBack={()=>{}} onChanged={()=>{}} session={session} department=""/>);for(const label of ["Solicitudes PDF","Gestión de compras","Pendientes de recibir","Recibidas para decisión","Solicitudes por departamento","Estado de la solicitud"])expect(html).toContain(label);expect(html).toContain("Después de recibirlos pasan a Recibidos");});
 it("abre las comunicaciones de Almacén primero por carpetas y después por estado",()=>{const html=renderToStaticMarkup(<MaintenanceCommunications view="requests" onNavigate={()=>{}} onBack={()=>{}} onChanged={()=>{}} session={session} department=""/>),source=readFileSync("src/components/vite/DocumentSystemModule.tsx","utf8"),styles=readFileSync("src/components/vite/maintenanceCommunications.css","utf8");for(const label of ["Comunicaciones de departamentos","Selecciona una carpeta","ALMACÉN · SOLICITUDES POR DEPARTAMENTO"])expect(html).toContain(label);expect(html).not.toContain('class="warehouse-inbox-status-tabs"');for(const label of ['label="Todas"','label="En tránsito"','label="Recibidas"','label="Rechazadas"'])expect(source).toContain(label);expect(source).toContain("['Tecnología','Servicios Generales','Recursos Humanos']");expect(styles).toContain('.mc-hub .warehouse-folder-grid>button');expect(styles).toContain('grid-template-areas:"icon eyebrow" "icon title" "icon count" "action action"');expect(styles).toContain('.mc-hub .warehouse-request-inbox .native-folder-toolbar');});
 it("organiza requerimientos por carpetas y valida la importación Excel",()=>{const requests=readFileSync("src/components/vite/WarehouseRequests.tsx","utf8"),center=readFileSync("src/components/vite/TicketCenter.tsx","utf8"),endpoint=readFileSync("api/InstitutionalDocumentEndpoints.cs","utf8");expect(requests).toContain("Requerimientos por departamento");expect(requests).toContain("Abrir carpeta");expect(center).toContain("Importar inventario desde Excel");expect(center).toContain('maintenanceInventoryImport.errors.length');expect(center).toContain("seriales duplicados fueron omitidos");expect(endpoint).toContain('"received"=>docs.Where(d=>d.Status=="received"||(d.Status=="approved"&&d.ReceivedUtc is not null))');});
 it("crea una solicitud PDF con varios equipos, serial por escáner y registro en historial",()=>{const composer=readFileSync("src/components/vite/WarehouseRequestComposer.tsx","utf8"),pdf=readFileSync("src/components/vite/warehouseRequestPdf.ts","utf8"),center=readFileSync("src/components/vite/TicketCenter.tsx","utf8"),endpoint=readFileSync("api/InstitutionalDocumentEndpoints.cs","utf8"),store=readFileSync("api/InstitutionalDocumentStore.cs","utf8"),detail=readFileSync("src/components/vite/InstitutionalDocumentDetail.tsx","utf8"),management=readFileSync("src/components/vite/WarehousePdfRequests.tsx","utf8");for(const marker of ['Agregar renglón','Devolución a Almacén','data-warehouse-scanner="true"','Escanea con el lector o escríbelo manualmente','form.append("channel","requirements")','form.append("recipientDepartment","Almacén")','form.append("sourceDepartment"'])expect(composer).toContain(marker);for(const marker of ['WarehouseRequestLineKind="EQUIPMENT"|"COMPONENT"|"RETURN"','REAL-WAREHOUSE-REQUEST-V319','SOLICITUD A ALMACÉN','FIRMA DE QUIEN RECIBE'])expect(pdf).toContain(marker);expect(composer).not.toContain("Departamento o destino");expect(center).toContain("<SentWarehouseRequestHistory");expect(center).not.toContain('title="Solicitudes enviadas a Almacén"');expect(management).toContain("Marcar recibido");expect(management).toContain("Imprimir");expect(endpoint).toContain('sourceDepartment is "Tecnología" or "Servicios Generales"');expect(store).toContain('d.Status!="received"');expect(detail).toContain("item.channel==='requirements'?item.status==='received'");expect(detail).toContain('Recibir con firma opcional');});
 it("comprueba límites y autorización del servidor para publicar o retirar",()=>{const code=readFileSync("api/MaintenanceTemplateEndpoints.cs","utf8");expect(code).toContain('a.Role!="Administrator"&&a.Team!="WAREHOUSE"');expect(code).toContain("10485760");expect(code).toContain('SequenceEqual("%PDF-"u8)');expect(code).toContain('RequireAuthorization("PortalUser")');expect(readFileSync("api/DatabaseMaintenanceTemplates.cs","utf8")).toContain("is_archived=@archived");});
});
