using Microsoft.Data.SqlClient;
partial class Database
{
    static readonly SemaphoreSlim TemplateSchemaLock=new(1,1);static bool templateSchemaReady;
    static async Task EnsureTemplateSchema(SqlConnection c,CancellationToken ct){if(templateSchemaReady)return;await TemplateSchemaLock.WaitAsync(ct);try{if(templateSchemaReady)return;await using var cmd=new SqlCommand("""
        IF OBJECT_ID(N'dbo.maintenance_templates',N'U') IS NULL
        CREATE TABLE dbo.maintenance_templates(id uniqueidentifier NOT NULL PRIMARY KEY DEFAULT(NEWID()),title nvarchar(160) NOT NULL,description nvarchar(2000) NULL,category varchar(20) NOT NULL,department varchar(40) NOT NULL,original_name nvarchar(200) NOT NULL,file_data varbinary(max) NOT NULL,file_size int NOT NULL,created_by_name nvarchar(160) NOT NULL,created_at datetime2(3) NOT NULL DEFAULT(SYSUTCDATETIME()),is_archived bit NOT NULL DEFAULT(0),updated_by_name nvarchar(160) NULL,updated_at datetime2(3) NULL);
        """,c);await cmd.ExecuteNonQueryAsync(ct);templateSchemaReady=true;}finally{TemplateSchemaLock.Release();}}
    public async Task<string?> MaintenanceTemplates(string role,string? team,CancellationToken ct){var dept=DepartmentForRole(role);var all=role=="Administrator"||team=="WAREHOUSE";if(!all&&dept=="")return null;await using var c=await Open(ct);await EnsureTemplateSchema(c,ct);await using var cmd=new SqlCommand("SELECT id,title,description,category,department,original_name originalName,file_size size,created_by_name createdByName,created_at createdAt,is_archived archived,updated_by_name updatedByName,updated_at updatedAt FROM dbo.maintenance_templates WHERE (@all=1 OR (is_archived=0 AND (department='ALL' OR department=@dept))) ORDER BY created_at DESC FOR JSON PATH",c);cmd.Parameters.AddWithValue("@all",all);cmd.Parameters.AddWithValue("@dept",dept);return (string?)await cmd.ExecuteScalarAsync(ct)??"[]";}
    public async Task<(byte[] Data,string Name)?> MaintenanceTemplateFile(Guid id,string role,string? team,CancellationToken ct){var dept=DepartmentForRole(role);var all=role=="Administrator"||team=="WAREHOUSE";if(!all&&dept=="")return null;await using var c=await Open(ct);await EnsureTemplateSchema(c,ct);await using var cmd=new SqlCommand("SELECT file_data,original_name FROM dbo.maintenance_templates WHERE id=@id AND (@all=1 OR (is_archived=0 AND (department='ALL' OR department=@dept)))",c);cmd.Parameters.AddWithValue("@id",id);cmd.Parameters.AddWithValue("@all",all);cmd.Parameters.AddWithValue("@dept",dept);await using var reader=await cmd.ExecuteReaderAsync(ct);return await reader.ReadAsync(ct)?((byte[])reader[0],reader.GetString(1)):null;}
    public async Task AddMaintenanceTemplate(string title,string description,string category,string department,string name,byte[] bytes,string actor,CancellationToken ct){await using var c=await Open(ct);await EnsureTemplateSchema(c,ct);await using var cmd=new SqlCommand("INSERT INTO dbo.maintenance_templates(title,description,category,department,original_name,file_data,file_size,created_by_name) VALUES(@title,@description,@category,@dept,@name,@bytes,@size,@actor)",c);cmd.Parameters.AddWithValue("@title",title);cmd.Parameters.AddWithValue("@description",Db(description));cmd.Parameters.AddWithValue("@category",category);cmd.Parameters.AddWithValue("@dept",department);cmd.Parameters.AddWithValue("@name",name);cmd.Parameters.AddWithValue("@bytes",bytes);cmd.Parameters.AddWithValue("@size",bytes.Length);cmd.Parameters.AddWithValue("@actor",actor);await cmd.ExecuteNonQueryAsync(ct);}
    public async Task<bool> ArchiveMaintenanceTemplate(Guid id,bool archived,string actor,CancellationToken ct){await using var c=await Open(ct);await EnsureTemplateSchema(c,ct);await using var cmd=new SqlCommand("UPDATE dbo.maintenance_templates SET is_archived=@archived,updated_by_name=@actor,updated_at=SYSUTCDATETIME() WHERE id=@id",c);cmd.Parameters.AddWithValue("@id",id);cmd.Parameters.AddWithValue("@archived",archived);cmd.Parameters.AddWithValue("@actor",actor);return await cmd.ExecuteNonQueryAsync(ct)==1;}
}
