using System.Security.Claims;
using System.Text.Json;

static class InstitutionalDocumentEndpoints
{
    static DocumentActor Actor(HttpContext c)=>new(c.User.FindFirstValue(ClaimTypes.NameIdentifier)??"",c.User.FindFirstValue(ClaimTypes.Role)??"",c.User.FindFirstValue("support_team")??"",c.User.FindFirstValue("display_name")??"Usuario",c.User.Identity?.Name??"");
    static string Area(HttpContext c)=>c.Request.Query["area"]=="communications"?"communications":"files";
    static string Channel(HttpContext c)=>c.Request.Query["channel"].ToString() switch { "requirements"=>"requirements", "all"=>"all", _=>"requests" };
    static IResult Error(string message,int status=422)=>Results.Json(new{message},statusCode:status);
    public static void MapInstitutionalDocumentEndpoints(this WebApplication app)
    {
        var group=app.MapGroup("/api/institutional-documents").RequireAuthorization("PortalUser");
        group.AddEndpointFilter(async(context,next)=>{if(!Actor(context.HttpContext).Allowed)return Results.Forbid();context.HttpContext.Response.Headers.CacheControl="private,no-store";return await next(context);});
        group.MapGet("/users",async(Database db,CancellationToken ct)=>Results.Content(await db.InstitutionalUsers(ct),"application/json"));
        group.MapGet("/overview",async(HttpContext c,Database db,CancellationToken ct)=>Results.Ok(await db.InstitutionalOverview(Actor(c),Area(c),Channel(c),ct)));
        group.MapGet("",async(HttpContext c,Database db,CancellationToken ct)=>{
            var a=Actor(c);IEnumerable<InstitutionalFile> docs=await db.InstitutionalList(a,Area(c),Channel(c),ct);var view=c.Request.Query["view"].ToString();var dept=c.Request.Query["department"].ToString();
            docs=docs.Where(d=>view=="trash"?d.Trashed&&d.IsOwner:!d.Trashed);docs=view switch{"mine"=>docs.Where(d=>d.IsOwner),"shared"=>docs.Where(d=>!d.IsOwner&&d.Shared(a)),"transit"=>docs.Where(d=>d.Status is "pending" or "correction_requested"),"received"=>docs.Where(d=>d.Status=="received"||(d.Status=="approved"&&d.ReceivedUtc is not null)),"rejected"=>docs.Where(d=>d.Status=="rejected"),"approved"=>docs.Where(d=>d.Status=="approved"),"sent"=>docs.Where(d=>d.IsOwner&&d.SentUtc is not null),_=>docs};if(dept!="")docs=docs.Where(d=>d.Department==dept);return Results.Ok(docs);
        });
        group.MapGet("/{id:long}",async(long id,HttpContext c,Database db,CancellationToken ct)=>{var d=await db.InstitutionalDetail(id,Actor(c),ct);return d is null?Results.NotFound():Results.Ok(d);});
        foreach(var route in new[]{"download","preview"}) group.MapGet("/{id:long}/"+route,async(long id,HttpContext c,Database db,CancellationToken ct)=>{var f=await db.InstitutionalBytes(id,Actor(c),ct);return f is null?Results.NotFound():Results.File(f.Value.Data,f.Value.Document.ContentType,f.Value.Document.OriginalFileName);});
        group.MapPost("",async(HttpContext c,Database db,LiveNotificationBroker broker,CancellationToken ct)=>{
            var a=Actor(c);if(!c.Request.HasFormContentType)return Error("Selecciona un archivo.");var form=await c.Request.ReadFormAsync(ct);var f=form.Files.GetFile("file");var area=form["area"]=="communications"?"communications":"files";var channel=form["channel"]=="requirements"?"requirements":"requests";var draft=string.Equals(form["draft"].ToString(),"true",StringComparison.OrdinalIgnoreCase);long? templateId=long.TryParse(form["templateId"].ToString(),out var parsedTemplateId)&&parsedTemplateId>0?parsedTemplateId:null;
            var title=form["title"].ToString().Trim();var description=form["description"].ToString().Trim();string? recipient=form["recipientUserName"].ToString().Trim();if(recipient=="")recipient=null;string? destination=form["recipientDepartment"].ToString().Trim();if(destination=="")destination=null;
            var sourceDepartment=a.Department;var requestedSource=form["sourceDepartment"].ToString().Trim();
            if(requestedSource!="")
            {
                if(requestedSource is not ("Tecnología" or "Servicios Generales"))return Error("El departamento solicitante no es válido.");
                if(!a.Manager&&requestedSource!=a.Department)return Results.Forbid();
                sourceDepartment=requestedSource;
            }
            if(f is null||f.Length is <1 or >10485760||form.Files.Count!=1||title.Length is <1 or >160||description.Length>2000)return Error("Indica título, descripción de hasta 2,000 caracteres y un archivo de hasta 10 MB.");
            if(area=="communications"&&!draft) {var departmentWarehouseRequest=channel=="requirements"&&destination=="Almacén"&&sourceDepartment is "Tecnología" or "Servicios Generales";if(channel=="requirements"&&!a.Manager&&!departmentWarehouseRequest)return Results.Forbid();if(!await db.InstitutionalRecipient(recipient,destination,ct)||recipient==a.Id||(recipient is null&&destination==sourceDepartment))return Error("Selecciona un departamento o destinatario válido distinto del remitente.");}
            if(area=="communications"&&draft){recipient=null;destination=null;channel="requests";}
            var filename=Path.GetFileName(f.FileName.Replace('\\','/'));if(filename.Length>180)return Error("El nombre del archivo es demasiado largo.");var ext=Path.GetExtension(filename).ToLowerInvariant();var mime=ext switch{".pdf"=>"application/pdf",".png"=>"image/png",".jpg" or ".jpeg"=>"image/jpeg",".docx"=>"application/vnd.openxmlformats-officedocument.wordprocessingml.document",".xlsx"=>"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",".txt"=>"text/plain",_=>""};if(mime=="")return Error("Formatos permitidos: PDF, PNG, JPG, DOCX, XLSX y TXT.");
            using var stream=new MemoryStream();await f.CopyToAsync(stream,ct);var bytes=stream.ToArray();if((ext==".pdf"&&(bytes.Length<5||!bytes.AsSpan(0,5).SequenceEqual("%PDF-"u8)))||(ext==".png"&&(bytes.Length<8||!bytes.AsSpan(0,8).SequenceEqual(new byte[]{137,80,78,71,13,10,26,10})))||((ext==".jpg"||ext==".jpeg")&&(bytes.Length<3||bytes[0]!=255||bytes[1]!=216||bytes[2]!=255))||((ext==".docx"||ext==".xlsx")&&(bytes.Length<4||bytes[0]!=80||bytes[1]!=75)))return Error("El contenido no corresponde al formato declarado.");
            var d=new InstitutionalFile{Area=area,Channel=channel,Title=title,Description=description,OriginalFileName=filename,ContentType=mime,Size=bytes.Length,OwnerUserName=a.Id,OwnerDisplayName=a.Name,OwnerLogin=a.Login,Department=sourceDepartment,RecipientDepartment=area=="communications"?destination:null,RecipientUserName=area=="communications"?recipient:null,Status=area=="communications"?(draft?"draft":"pending"):"active",SentUtc=area=="communications"&&!draft?DateTime.UtcNow:null,TemplateId=area=="communications"&&draft?templateId:null};d.Id=draft&&templateId is long tid?await db.InstitutionalArchiveTemplatePdf(a,tid,d,bytes,ct):await db.InstitutionalUpload(d,bytes,ct);broker.Publish("institutional-document-created");return Results.Ok(d.For(a));
        }).RequireRateLimiting("sensitive-write");
        group.MapPost("/{id:long}/actions/{action}",async(long id,string action,InstitutionalAction body,HttpContext c,Database db,LiveNotificationBroker broker,CancellationToken ct)=>{
            if(action is not ("receive" or "move" or "sign" or "approve" or "reject" or "correction" or "edit" or "share" or "unshare" or "trash" or "restore" or "purge" or "resend" or "send"))return Error("Acción no válida.");
            if(!double.IsFinite(body.SealX)||!double.IsFinite(body.SealY)||body.SealX is <2 or >98||body.SealY is <2 or >98)return Error("El sello debe quedar dentro de la página.");
            if(action=="edit"&&(string.IsNullOrWhiteSpace(body.Title)||body.Title.Length>160||(body.Description?.Length??0)>2000))return Error("Revisa el título y la descripción.");
            if(action is "approve" or "reject" or "correction"&&(string.IsNullOrWhiteSpace(body.Note)||body.Note.Trim().Length is <5 or >2000))return Error("Indica un motivo de 5 a 2,000 caracteres.");
            if(action=="sign"&&!MaintenanceDocumentEndpoints.ValidSignature(body.SignatureData))return Error("Dibuja una firma PNG válida.");
            if(action=="share"&&!await db.InstitutionalRecipient(body.RecipientUserName,body.RecipientDepartment,ct))return Error("Selecciona un destinatario válido.");
            if(action=="send"&&!await db.InstitutionalRecipient(body.RecipientUserName,body.RecipientDepartment,ct))return Error("Selecciona un destinatario válido.");
            var error=await db.InstitutionalChange(id,Actor(c),action,body,ct);if(error is not null)return Error(error,409);broker.Publish("institutional-document-updated");return Results.Ok(new{ok=true});
        }).RequireRateLimiting("sensitive-write");
        // Verification remains authenticated and follows the same document access checks.
        group.MapGet("/verify/{token}",async(string token,HttpContext c,Database db,CancellationToken ct)=>{var a=Actor(c);var docs=(await db.InstitutionalList(a,"communications","requests",ct)).Concat(await db.InstitutionalList(a,"communications","requirements",ct));var d=docs.FirstOrDefault(x=>x.VerificationToken==token&&x.ReceivedUtc is not null&&!x.Trashed);return d is null?Results.NotFound():Results.Ok(new{valid=true,institution="REAL · Grupo Tejeda",d.Title,d.ReceiptCode,d.ReceivedUtc,d.ReceiverDisplayName,d.ReceiverLogin,d.Status,statusText=d.Status switch{"pending"=>"En tránsito","received"=>"Recibido","approved"=>"Autorizado","rejected"=>"Rechazado","correction_requested"=>"Corrección solicitada",_=>d.Status},steps=new[]{new{label="Enviado",complete=d.SentUtc is not null,at=d.SentUtc,actor=(string?)d.OwnerDisplayName},new{label="Recibido en destino",complete=d.ReceivedUtc is not null,at=d.ReceivedUtc,actor=d.ReceiverDisplayName},new{label=d.Status=="rejected"?"Rechazado":"Autorizado",complete=d.Status is "approved" or "rejected",at=d.DecisionUtc,actor=d.DecisionBy}},history=d.History.Select(h=>new{h.Action,h.Actor,h.Login,h.At,h.PreviousStatus,h.ReceiptCode,h.ReceiverLogin,h.ReceivedUtc})});});
        group.MapGet("/templates",async(HttpContext c,Database db,CancellationToken ct)=>Results.Ok(await db.InstitutionalTemplates(Actor(c),ct)));
        group.MapPost("/templates",async(EditableTemplateInput b,HttpContext c,Database db,CancellationToken ct)=>{if(string.IsNullOrWhiteSpace(b.Name)||b.Name.Length>160||string.IsNullOrWhiteSpace(b.Content)||b.Content.Length>100000)return Error("Nombre de hasta 160 caracteres y contenido de hasta 100,000.");try{using var parsed=JsonDocument.Parse(b.Content);if(parsed.RootElement.ValueKind!=JsonValueKind.Object)return Error("Plantilla no válida.");}catch(JsonException){return Error("Plantilla no válida.");}var a=Actor(c);var id=await db.InstitutionalSaveTemplate(a,b.Id,b.Name.Trim(),b.Content,ct);return id is null?Results.Forbid():Results.Ok(new InstitutionalTemplate(id.Value,b.Name.Trim(),b.Content,a.Department,a.Id,false,DateTime.UtcNow));}).RequireRateLimiting("sensitive-write");
        group.MapDelete("/templates/{id:long}",async(long id,HttpContext c,Database db,CancellationToken ct)=>await db.InstitutionalDeleteTemplate(Actor(c),id,ct)?Results.NoContent():Results.NotFound()).RequireRateLimiting("sensitive-write");
    }
}
record EditableTemplateInput(long? Id,string Name,string Content);
